### ISSUE TITLE
bug : Node must exists.

### ISSUE THREAD

**Issue by amin101** [lazychaser/laravel-nestedset#101]
hi,thanks for great package.
First node `_lft` value  is always `0` , so when i try to move  a node before or after first node , an exception throw:
```php
LogicException in NodeTrait.php line 1144: Node must exists.
``` 
it's because of ` if ( ! $node->getLft() |....`

**Comment by lazychaser** [comment]
Left of first node is 1. Make sure that you have saved the node.

**Comment by amin101** [comment]
I don't know why it was `0` at first. after recreating db table it solved!

**Comment by khemrajregmi** [comment]
I manually make the left node 1 in database  but also it is not solved
