### ISSUE TITLE
root node creation doesn't work

### ISSUE THREAD

**Issue by dinobot71** [lazychaser/laravel-nestedset#107]
Hi, I spent several hours trying to get ::create to work, just create a simple root node in an empty table, and it doesn't work. Does this component not support starting trees from an empty table?  Why not?  After so many hours of frustration I'm going to go look for another component but I'll file the issue here for others who have the same problem.

I followed the recipe of extending Model, and creating a table with the appropriate columns, but when I invoke the static model ::create method, I get:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "_lft" violates not-null constraint
DETAIL:  Failing row contains (null, null, null, 1, test, null, null).' in /.../vendor/illuminate/database/Connection.php:335

When the left/right nodes should be set to 0 and 1 (I think) since its the root node.

My Model looks like:

class MyNode extends Model {
    protected $fillable = array('name', 'field1', 'field2');
    public $timestamps  = false;
    protected $table    = 'my_custom_table_name';
}

and the table:

# \d my_custom_table_name
                                  Table "public.my_custom_table_name"
  Column   |          Type          |                              Modifiers                              
-----------+------------------------+---------------------------------------------------------------------
 _lft      | integer                | not null
 _rgt      | integer                | not null
 parent_id | integer                | 
 id        | integer                | not null default nextval('my_custom_table_name_id_seq'::regclass)
...

and just trying to create a root node on empty table:

 $node = MyNode ::create(
        [
            'name' => 'test',
            'children' =>
            [
                [ 'name' => 'test2' ],
                [ 'name' => 'test3' ],
            ],
        ]);

At which point it fails with the above database error message.

I looked through the source code and the test cases, and read the markdown page several times, and I'm not seeing anything I did wrong according the documentation and the examples in the test cases.  I also googled around to see if I could find other examples, tutorials or similar errors to see if I did something obviously wrong.

**Comment by dinobot71** [comment]
I doubled down on the Laravel end of this and managed to figure it out.  It seems if you are using this outside of Laravel (via Capsule); depending on how you setup Capsule, it will impact things inside the model machinery and how it interacts with this nested set component.  

I'm using illuminate/database, outside of the web app framework, and I had followed their recipe for setting up Capsule, but I didn't set up the *optional* event dispatcher...I had no reason to think I would need it.  

Well, nested set is a reason :( 

when I went back and added:

$capsule->setEventDispatcher(new Dispatcher(new Container));

To the Capsule setup code...now everything in NestedSet seems to work as expected...and no nasty tracebacks :)

The Capsule setup code for working outside of the web app, when using 

https://github.com/illuminate/database

is:

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Events\Dispatcher;
use Illuminate\Container\Container;

$capsule = new Capsule;
$capsule->setEventDispatcher(new Dispatcher(new Container));
$capsule->addConnection($factoryConfig);
$capsule->setAsGlobal();
$capsule->bootEloquent();

Here '$factoryConfig' is just my database connection settings.

Not sure why not having an event dispatcher breaks NestedSet.  Its not listed as a requirement in your documentation.  I would ask that you update your documentation, if I had known I needed this optional feature, I could have saved hours of debugging.

**Comment by lazychaser** [comment]
Yes, that's how it works. Since Node is a trait, I didn't want to override basic methods like `save` or `delete`, so it uses event system to work.

**Comment by dinobot71** [comment]
Makes sense.  But...can you add a paragraph to installation documentation about "using outside of a web app"?
............
Using Outside of a Web 

Please ensure your database adapter  is fully setup to support core Eloquent functionality such as the event system (so operations like save work correctly).  As an example users of Illuminate\Database should ensure the optional event dispatcher is configured.
............

I know you can't be documenting how your stuff inter-operates with every package out there, but using your stuff outside of a web app is a pretty generic case and it would help others (like me) who are working in that mode to more easily / quickly integrate your package with tips like this.

After all this means more people finding  your package useful, so its good for everyone if you make it more clear how to use outside of a web app.

**Comment by lazychaser** [comment]
@dinobot71 could you create a pull request? I would merge it

**Comment by Vuishnak** [comment]
@dinobot71 hi! I think, I have the same problem, but my Eloquent ORM works without Capsule.
I have the structure of my projects like this: 

- projects
   -- Dashboard
       --- app
       --- bootstrap
       --- ...
   -- Blog
- vendor

But when I tried to create root, i have _lft=0 and _rgt=0. Don't understand, what a problem? Can you help me?

**Comment by dinobot71** [comment]
Hey, just back from vacation, will reply as soon as I can, stay tuned.

 

(^_^)/

Mike.
