### ISSUE TITLE
bool = Category::isBroken(), and $data = Category::countErrors() not work.....

### ISSUE THREAD

**Issue by AlehDev** [lazychaser/laravel-nestedset#110]
Hi. 
$bool = Category::isBroken(), and $data = Category::countErrors() not work with SoftDeletes in Latavel =<5.2.36
Latavel Latavel >=5.2.35 is work...

**Comment by lazychaser** [comment]
Please, describe your problem more specificially. What those function return and what is expected?

**Comment by trixanapp** [comment]
Yes.
My Category Model:

``
use Kalnoy\Nestedset\NodeTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class BlogCategory extends Model
{
    use NodeTrait, BlogCategoryAttribute, BlogCategoryRelationship, SoftDeletes;

    protected $connection = 'my-conn';

    protected $table = 'blog_categories';

    protected $fillable = ['slug', 'name'];

    protected $guarded = ['id'];

    protected $dates = ['deleted_at'];
	............................
``

My Migrate:

``
Schema::connection($connection)->create('blog_categories', function (Blueprint $table) {

            $table->increments('id');
            NestedSet::columns($table);
            $table->string('slug')->unique();
            $table->string('name');
            $table->timestamps();
            $table->softDeletes();
			.................
``

My EloquentBlogCategoryRepository:

``
public function updateSort($hierarchy)
    {
        if (BlogCategory::isBroken()) {
            BlogCategory::fixTree();
        }
		
		etc..................
``

Log Error:

``
2016-06-24 14:09:29] local.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'blog_categories.deleted_at' in 'where clause' in /home/vagrant/code/trixanapp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
Stack trace:
Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'blog_categories.deleted_at' in 'where clause' (SQL: select (select count(1) from `blog_categories` where `blog_categories`.`deleted_at` is null and "query.file" <> "/home/vagrant/code/trixanapp/app/Repositories/Backend/Modules/Blog/EloquentBlogCategoryRepository.php" and "query.line" <> "341" and (`_lft` >= `_rgt` or (`_rgt` - `_lft`) % 2 = 0)) as `oddness`, (select count(1) from `blog_categories` as `c1`, `blog_categories` `c2` where `blog_categories`.`deleted_at` is null and "query.file" <> "/home/vagrant/code/trixanapp/app/Repositories/Backend/Modules/Blog/EloquentBlogCategoryRepository.php" and "query.line" <> "341" and `c1`.id < `c2`.id and (`c1`.`_lft`=`c2`.`_lft` or `c1`.`_rgt`=`c2`.`_rgt` or `c1`.`_lft`=`c2`.`_rgt` or `c1`.`_rgt`=`c2`.`_lft`)) as `duplicates`, (select count(1) from `blog_categories` as `c`, `blog_categories` as `p`, `blog_categories` as `i` where `blog_categories`.`deleted_at` is null and "query.file" <> "/home/vagrant/code/trixanapp/app/Repositories/Backend/Modules/Blog/EloquentBlogCategoryRepository.php" and "query.line" <> "341" and `c`.`parent_id`=`p`.`id` and `i`.`id` <> `p`.`id` and `i`.`id` <> `c`.`id` and (`c`.`_lft` not between `p`.`_lft` and `p`.`_rgt` or `c`.`_lft` between `i`.`_lft` and `i`.`_rgt` and `i`.`_lft` between `p`.`_lft` and `p`.`_rgt`)) as `wrong_parent`, (select count(1) from `blog_categories` where `blog_categories`.`deleted_at` is null and "query.file" <> "/home/vagrant/code/trixanapp/app/Repositories/Backend/Modules/Blog/EloquentBlogCategoryRepository.php" and "query.line" <> "341" and (`parent_id` is not null and not exists (select 1 from `blog_categories` as `p` where `blog_categories`.`deleted_at` is null and "query.file" <> "/home/vagrant/code/trixanapp/app/Repositories/Backend/Modules/Blog/EloquentBlogCategoryRepository.php" and "query.line" <> "341" and `blog_categories`.`parent_id` = `p`.`id` limit 1))) as `missing_parent` limit 1) in /home/vagrant/code/trixanapp/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713
``

**Comment by AlehDev** [comment]
В общем, пока как **временное** решение сделал так: :)))

```/**
     * Get statistics of errors of the tree.
     *
     * @since 2.0
     *
     * @return array
     */
    public function countErrors()
    {
        $checks = [];

        // Check if lft and rgt values are ok
        $checks['oddness'] = $this->getOdnessQuery();

        // Check if lft and rgt values are unique
        $checks['duplicates'] = $this->getDuplicatesQuery();

        // Check if parent_id is set correctly
        $checks['wrong_parent'] = $this->getWrongParentQuery();

        // Check for nodes that have missing parent
        $checks['missing_parent' ] = $this->getMissingParentQuery();

        $query = $this->query->newQuery();

        foreach ($checks as $key => $inner) {
		
			unset($inner->wheres[0]); // <= ТУТА <= 
		
            $inner->selectRaw('count(1)');

            $query->selectSub($inner, $key);
        }

        return (array)$query->first();
    }
```
Потом будет время, буду разбираться...
Заранее спасибо!
