### ISSUE TITLE
List of childs looses its original parent

### ISSUE THREAD

**Issue by stefanius** [lazychaser/laravel-nestedset#112]
Hi,

I have a simple tree which always has maximum dept of 1 child. Consider my (companies / departments) tree below:

```
Microsoft
  Sales
  Research
Apple
  Development
  Support
  Sales
```

When I will do a Search on 'Sales' it will only gives me the children. In my view, I want to display the output with the toTree() method and on that moment Apple->sales is no more. See therefore: https://github.com/lazychaser/laravel-nestedset/blob/v4/src/Collection.php#L95

In the same view, when there is a list of parents, everything is OK. My first impression that I want to recieve the parent when I query on a child. Does the package provide a solution for this or do you have a another sugestion?

**Comment by lazychaser** [comment]
You can inspect [this method](https://github.com/lazychaser/laravel-nestedset/blob/v4/src/QueryBuilder.php#L83). You can select all ancestors of all selected nodes and then add them to the collection and build a tree then. But you'll need to do this on your own using `or`:

```
// For each node
$query->orWhereRaw($node->getLft().' between _lft and _rgt');

// Exclude ids
$query->whereNotIn('id', $nodes->pluck('id'));
```

**Comment by stefanius** [comment]
Thanks, I will try this solution.

**Comment by stefanius** [comment]
Thanks, I used it as part of a greater solution.
