### ISSUE TITLE
Descendants and self

### ISSUE THREAD

**Issue by it-can** [lazychaser/laravel-nestedset#113]
I want all id's from the descendants and the current category in a array, so I do this:

```
$category = Category::findOrFail(8);
$ids = $category->descendants->pluck('id')->toArray();
```

this will print a array with these values:

```
array:2 [
  0 => 17
  1 => 18
]
```

So now I have to do this:

```
$category = Category::findOrFail(8);
$ids = $category->descendants->pluck('id')->push($category->id)->toArray();

array:3 [
  0 => 17
  1 => 18
  2 => 8
]
```

This is correct, but I also want the id of the category in there (8). Is there a method like `descendantsandself` or something?

**Comment by lazychaser** [comment]
You already have that id, you can append it to the array.

2016-07-06 11:16 GMT+03:00 M. Vugteveen <notifications@github.com>:

> I want all id's from the descendants and the current category in a array,
> so I do this:
>
> $category = Category::findOrFail(8);
> $ids = $category->descendants->pluck('id')->toArray();
>
> this will print a array with these values:
>
> array:2 [▼
>   0 => 17
>   1 => 18
> ]
>
> This is correct, but I also want the id of the category in there (8). Is
> there a method like descendantsandself or something?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lazychaser/laravel-nestedset/issues/113>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AB_3CLuAv66ow1n87rx6i4FFFi4Coa7bks5qS2RqgaJpZM4JF2Zt>
> .
>



-- 
Best regards, Alexander Kalnoy.
