### ISSUE TITLE
You can give me a demo of 5.2 laravel are very thankful for that

### ISSUE THREAD

**Issue by thandonguocmo2020** [lazychaser/laravel-nestedset#118]
I just found your package but I have difficulty to integrate it and my app. I have used demo 5.0 but apparently it does not work well with laravel 5.2.

**Comment by jspekken** [comment]
@thandonguocmo2020 We are running laravel-nestedset successfully on several 5.2 sites. Can you please explain what you're seeing when running this package on 5.2?
