### ISSUE TITLE
Laravel 4.2

### ISSUE THREAD

**Issue by MCON** [lazychaser/laravel-nestedset#124]
How to use it with laravel 4.2? (laravel-nestedset v3 or laravel-nestedset v2)
Tried to use instruction but it did not work.

**Comment by lazychaser** [comment]
For Laravel 4.2 use `2.*` version. [Here](https://github.com/lazychaser/laravel-nestedset/tree/93981749a1b3e483aee39d01bbd00b2be27145bb) is the latest release is docs.

**Comment by MCON** [comment]
Still have error:
\FatalErrorException' with message 'Trait 'Kalnoy\Nestedset' not found' 

I think i need to write in some provider in app.php or smth.

**Comment by lazychaser** [comment]
https://github.com/lazychaser/laravel-nestedset/tree/93981749a1b3e483aee39d01bbd00b2be27145bb#the-model
