### ISSUE TITLE
Integrity constraint violation: 1048 Column '_lft' cannot be null on $descendant->appendToNode($node)->save();

### ISSUE THREAD

**Issue by xenDE** [lazychaser/laravel-nestedset#125]
my _RebuildTree() for saving new ordered tree makes problem on a new project:

`local.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column '_lft' cannot be null in /home/vagrant/Code/dahops/private/vendor/laravel/framework/src/Illuminate/Database/Connection.php:505`

it was working fine on last project wit Laravel 5.2 and "kalnoy/nestedset": "^4.0",

now I'm on "laravel/framework": "5.3.*", and "kalnoy/nestedset": "dev-master"

The Error comes on `$descendant->appendToNode($node)->save();`

I have to change `$descendant->appendTo($node)->save();` to `$descendant->appendToNode($node)->save();`

i don't find the mistake/change.

```
class District extends Model
{

	use NodeTrait;
	use SoftDeletes;
[...]
	public static function _rebuildTree($data_array, $front_slug = 'district')
	{
		$return = true;
		if (is_array($data_array)) {
			foreach ($data_array as $data_node) {
				$node = self::find($data_node['id']);
				$node->save();
				//loop recursively through the children
				if (isset($data_node['children']) && is_array($data_node['children'])) {
					foreach ($data_node['children'] as $data_node_child) {
						//append the children to their (old/new)parents
						$descendant = self::find($data_node_child['id']);
						#old: $descendant->appendTo($node)->save();
						$descendant->appendToNode($node)->save();
// ^^^here comes the error!
						//ordering trick here, shift the descendants to the bottom to get the right order at the end
						$shift = count($descendant->getSiblings());
						$descendant->down($shift);
						$my_return = self::_rebuildTree($data_node['children'], $node->slug_combined);
						if (true !== $my_return)
							$return = $my_return;
					}
				}
			}
		}
		return $return;
	}

}
```

The bad SQL - copy from Debugbar - is:
`update `districts` set `_lft` = , `_rgt` = , `updated_at` = 2016-08-11 16:19:31 where `id` = 8)`

What can i check?

best regards,
Daniel

**Comment by lazychaser** [comment]
Hi, Laravel 5.3 is not supported yet, I will be checking everything after 5.3 is released

**Comment by xenDE** [comment]
Hi, ok.

removed my own _rebuildTree() and use now Kalnoy\Nestedset\QueryBuilder::rebuildTree().

I find the SQL updates in the debugbar - but nothing changes in the database.
need to debug more.

```
update `districts` set `_lft` = '4', `_rgt` = '5', `updated_at` = '2016-08-12 11:39:40' where `id` = '8'
update `districts` set `_lft` = '6', `_rgt` = '7', `updated_at` = '2016-08-12 11:39:40' where `id` = '4'
update `districts` set `_lft` = '8', `_rgt` = '9', `updated_at` = '2016-08-12 11:39:40' where `id` = '5'
update `districts` set `_lft` = '10', `_rgt` = '11', `updated_at` = '2016-08-12 11:39:40' where `id` = '6'
update `districts` set `_lft` = '12', `_rgt` = '13', `updated_at` = '2016-08-12 11:39:40' where `id` = '7'
```

the querys run fine if i manual run them.

if anybody has any ideas, please comment.

**Comment by xenDE** [comment]
No idea why the updates do not change the database - update forms are working, only the ->save() inside Kalnoy\Nestedset\QueryBuilder does not change the data in the database.
but the debugbar shows the update statemens.

**Comment by lazychaser** [comment]
Database transaction is not commited, but I don't know why

**Comment by wppd** [comment]
I've encountered the  problem yesterday with 4.1.6 in laravel 5.3.15

what I did is, update an existing node with new parent id, then the error " Integrity constraint violation: 1048 Column '_lft' cannot be null" pops up. Tried to track down but couldn't find out anything.

 I re-migrated the database and it's suddenly gone but not sure if it'll ever happens again. So I make "_lft" and "_rgt" nullable and after update, I always do `Category::fixTree()`... It's so hacky.

@lazychaser could it be possible, a warning when `_lft` null or a default value or something?

**Comment by lazychaser** [comment]
@wppd Tell me exactly what you're doing

**Comment by wppd** [comment]
@lazychaser thanks for you reply.

I think the root cause is that I make "_lft" and "_rgt" fillable. I didn't remove "_lft" and "_rgt" from arguments when updating the node.

**Comment by lazychaser** [comment]
@wppd why would you make `_lft` and `_rgt` fillable?

**Comment by wppd** [comment]
@lazychaser haha, some mistake when creating the model file.
