### ISSUE TITLE
Not compatible with October CMS

### ISSUE THREAD

**Issue by dinobot71** [lazychaser/laravel-nestedset#127]
probably nothing you can do on this one; you can't necessarily have the same LTS policy as other projects but...

```
    /*
     * !! Hack Alert !! 
     * 
     * ->withDepth()
     * 
     * NOTE: we can't use withDepth() because as its implemented in kalnoy/nestedset
     * it relies on Laravel 5.2 features; scoped queries, and methjods like toBase().
     * They don't exist in Laravel 5.1.  October CMS is based on...you guessed it,
     * Laravel 5.1 (as of a week ago)...with no big rush to upgrade.  So...withDepth()
     * will not be compatible with October CMS for months at least.
     * 
     * Le Sigh.  You try to reuse off the shelf, and this is what happens.  Anyways,
     * can work around below by replacing withDepth() with the SQL that it actually 
     * unrolls to.
     * 
     */

    ->select('*')
    ->selectRaw('(select count(1) - 1 from "'.self::getTablename().'" as "_d" where "'.self::getTablename().'"."_lft" between "_d"."_lft" and "_d"."_rgt") as depth')
```

Basically I'm trying to use nested set within October and out of the box its a non-starter, because withDepth() depends on Laravel 5.2 features (i.e. toBase() and related methods).  

October has no current plan to be on 5.2...they are LTS wioth 5.1.

So not much can be done I guess, but its worth highlighting this for other users who are trying to use this with October and get mysterious errors.

**Comment by Muffinman** [comment]
Note that withDepth() also seems to fail with Laravel 5.3 if you have `strict => true` in your PDO settings.
