### ISSUE TITLE
Scoping causes uncalculated _lft/_rgt

### ISSUE THREAD

**Issue by mgsmus** [lazychaser/laravel-nestedset#128]
Laravel Framework version 5.2.45 (Fresh install)
PHP 5.6.15

composer.json
```json
"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.2.*",
    "kalnoy/nestedset": "^4.1",
},
```

Page.php
```php
namespace App;

use Kalnoy\Nestedset\NodeTrait;
use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    use NodeTrait;

    protected $table = 'pages';

    protected $guarded = ['id'];

    protected function getScopeAttributes()
    {
        return ['locale'];
    }
}
```

Model event (Removing this event doesn't affect to issue)
Every record has a locale value. I'm inserting here automatically
```php
// in AppServiceProvider::boot
Page::creating(function($page) {
    $page->locale = input_locale(); // this helper function returns active locale (en, de, fr...)
});
```

Let's create some root pages
```php
Page::create([
    'title' => 'Test Page',
    'slug' => 'test-page'
]);

Page::create([
    'title' => 'Test Page 2',
    'slug' => 'test-page-2'
]);

Page::create([
    'title' => 'Test Page 3',
    'slug' => 'test-page-3'
]);
```

Result (_lft _rgt values are incorrect)

| id | locale |    title    |    slug     | _lft | _rgt | parent_id |
|----|--------|-------------|-------------|------|------|-----------|
|  1 | en     | Test Page   | test-page   |    1 |    2 | null      |
|  2 | en     | Test Page 2 | test-page-2 |    1 |    2 | null      |
|  3 | en     | Test Page 3 | test-page-3 |    1 |    2 | null      |

If I remove getScopeAttributes() from Page model and insert records again, here's the result (correct one):

| id | locale |    title    |    slug     | _lft | _rgt | parent_id |
|----|--------|-------------|-------------|------|------|-----------|
|  1 | en     | Test Page   | test-page   |    1 |    2 | null      |
|  2 | en     | Test Page 2 | test-page-2 |    3 |    4 | null      |
|  3 | en     | Test Page 3 | test-page-3 |    5 |    6 | null      |

**Comment by mgsmus** [comment]
```php
Page::create([
    'title' => 'Test Page',
    'slug' => 'test-page',
    'locale' =>'en'
]);
```

This works. It seems calculation happens before Page::creating event and it doesn't see my locale value.

**Comment by cosmorogers** [comment]
I've fudged a fix for this, on line 767 change newNestedSetQuery to just newQuery
https://github.com/lazychaser/laravel-nestedset/blob/v4/src/QueryBuilder.php#L767

**Comment by lazychaser** [comment]
Try putting locale assignment in `saving` event and a better place for this is `boot` method.

```php
    protected static function boot()
    {
        static::saving(...);
        
        parent::boot();
    }
```
