### ISSUE TITLE
Issues with firing events

### ISSUE THREAD

**Issue by Azirius** [lazychaser/laravel-nestedset#129]
I've been having an issue with this package for quite a while after having updating to Laravel 5.3.

I'm not sure if the issue is related, but it's during the events being fired, in that they use transactions. I noticed in my MySQL logs that `ROLLBACK` was present.

After a bit of digging (and an awful lot of head scratching) I've discovered the cause.

In the `NodeTrait` trait there is a call to `static:saved` method that's never called, which I can only assume is caused by the fact that the call to `static:saving` method returns `null`.

``` php
// snipped
        static::saving(function ($model) {
            $model->getConnection()->beginTransaction();

            return $model->callPendingAction();
        });

        static::saved(function ($model) {
            $model->getConnection()->commit();
        });
// snipped
```

I have resolved the issue simply by removing the return statement and moving the contents of the closure from the `static::saved` method into the `static::saving` method and then everything works again.

I'm not sure if there's a difference in how `null` is evaluated between Laravel 5.2 and 5.3 but this issue was not present for me prior.

`$model->callPendingAction();` appears to be the 'main offender' here, due to the fact it is returning `null` or `void` or nothing at all. 

So, I've had to deal with this in my own way, if someone could issue an 'official fix' eventually though that would be perfect :] 

Hope I have provided enough information!

**Comment by xenDE** [comment]
Big Thanks, looks like a solution for my problem here: https://github.com/lazychaser/laravel-nestedset/issues/125#issuecomment-239426229
