### ISSUE TITLE
Have a nested set of different instance

### ISSUE THREAD

**Issue by AeonDave** [lazychaser/laravel-nestedset#134]
Hello,
Is possible to have a nested set of different instance?
example:

Brand - Shop - Client Models

Brand could have Shop and Client
Shop could have Client

```

$brand = new Brand;
$shop1 = new Shop;
$shop2 = new Shop;

$brand->appendNode($shop1);
$brand->appendNode($shop2);

$client1 = new Client;
$client2 = new Client;
$client3 = new Client;

$shop1->appendNode($client1);
$shop2->appendNode($client2);
$brand->appendNode($client3);
```

---

Brand
---Shop1
------Client1
---Shop2
------Client2
---Client3

Thank You

**Comment by AeonDave** [comment]
Now with this example i get:

Argument 1 passed to Brand::appendNode() must be an instance of Brand, instance of Shop given

Model Brand:
```
class Brand extends Model {
  use NodeTrait;
   ...
```

Model Shop:
```
class Shop extends Model {
  use NodeTrait;
  ...
```

**Comment by lazychaser** [comment]
Seems like you don't need nested set package at all. You can set everything up using `BelongsTo` relationship.

**Comment by AeonDave** [comment]
no i cannot.. there are other nodes in the middle. this is the easiest status.
is possible to nest multi nodes?

**Comment by lazychaser** [comment]
You can use `belongsTo` with scoping feature (see docs).

**Comment by AeonDave** [comment]
so i cannot use nested set with multiple models. ok

**Comment by lazychaser** [comment]
You can. This will be a single table inheritance pattern. But all models will be a variation of one base model.

**Comment by AeonDave** [comment]
mm ok, but how? any example?
