### ISSUE TITLE
Package as Service Provider with a Facade.

### ISSUE THREAD

**Issue by cirdog** [lazychaser/laravel-nestedset#135]
Hi Alexander,

Firstly thanks for your contribution.

As I was trying out your package, I noticed that it's not used as a Service Provider nor it offers a facade. I figured from the installation documentation that it's directly used as "static methods".

I wonder if there is any special rationale behind this choice? And would you kindly consider making it a Service Provider? And if not, what is your main concern against it?

Thanks again.

-Godric

**Comment by lazychaser** [comment]
Well, there is no configuration needed, no extra resources, everyhing is registered by the trait. And few helper methods are available via static methods.
