### ISSUE TITLE
Limiting number of results per depth?

### ISSUE THREAD

**Issue by asdfgasd815f** [lazychaser/laravel-nestedset#138]
Say I have a tree that looks like this:

```
- 1 (top-level)
-- 2
--- 3
--- 4
--- 5
-- 6
-- 7
-- 8
- 9 (top-level)
```

Is it possible to query and limit the number of results returned per depth?

For example, if I want to limit the number of results by the following rules:

- Up to 10 top-level nodes
- Up to 3 level-1 nodes
- Up to 2 level-2 nodes

The end result should look like this:

```
- 1 (top-level)
-- 2
--- 3
--- 4
-- 6
-- 7
- 9 (top-level)
```

Is this possible?

**Comment by lazychaser** [comment]
This package doesn't provide such feature.

**Comment by asdfgasd815f** [comment]
Any idea how this could be achieved?

**Comment by lazychaser** [comment]
I don't know. But I'm sure there is other way to solve your problem without per-depth limiting
