### ISSUE TITLE
Bad order when toTree

### ISSUE THREAD

**Issue by Cyber-host** [lazychaser/laravel-nestedset#140]
Hi. When I get data from table with `->defaultOrder()` order is fine, but when I do `->toTree` order is bad. Thanks.

**Comment by lazychaser** [comment]
Hi. Order of items of same level is maintained  when building a tree.

**Comment by Cyber-host** [comment]
hm.. when I do `toFlatTree` is good, but `toTree` sort by `id` =(

**Comment by lazychaser** [comment]
`toFlatTree` does almost the same thing as `toTree`. Please, check your code, the problem is not in this package

**Comment by lazychaser** [comment]
Or provide failing test
