### ISSUE TITLE
Get parent of node with max depth

### ISSUE THREAD

**Issue by haipham** [lazychaser/laravel-nestedset#141]
Hi every.

I have a below tree:

-Parent
--Child 1
**---Child 1.1**
---Child 1.2
--Child 2
---Child 2.1
---Child 2.2

I focus to "Child 1.1" node and get prent's it (with max depth: "Child 1") with code:

$parent = Category::withDepth()->whereAncestorOf($node)->get()->max(); 

It work. But any other ways to get parent's "Child 1.1" with max depth (Child 1.1) which better above code?

Thank you.

**Comment by lazychaser** [comment]
`$child->parent`

**Comment by haipham** [comment]
Cool. Thank you.
