### ISSUE TITLE
Trait doesn't work

### ISSUE THREAD

**Issue by Vuishnak** [lazychaser/laravel-nestedset#142]
Hi. I have the problem with this package.
When i tried to create new root attributes (_lft, _rgt) have 0 as value, always.
Of course, children doesn't creating too.

But I have my own structure of project like this:
/projects
--- Dashboard
------ app
------ bootstrap
------ ... (structure of laravel)
--- Blog
/vendor

So, all my vendors can be used in all projects.
And all of this stuff works (including DB and Eloquent), but I don't know, what to do with this problem.
Thanks!

**Comment by lazychaser** [comment]
Ты используешь какие-нибудь другие расширения?

**Comment by Vuishnak** [comment]
Да, конечно. Много

**Comment by lazychaser** [comment]
Скорее всего там конфликт

**Comment by Vuishnak** [comment]
В чем может заключаться конфликт? Нужно понять, с каким расширением конфликтует пакет...

**Comment by Vuishnak** [comment]
It works now, but I don't know, why. I did migrate refresh. Maybe it is a reason...
