### ISSUE TITLE
Ancestors eager loading?

### ISSUE THREAD

**Issue by infinitation** [lazychaser/laravel-nestedset#143]
Any chance there is an easy way to eager load ancestors? I see there is a way to do it with dependents but I would love to be able to eager load ancestors so the SQL calls are minimized. Any thoughts or guidance is appreciated.

**Comment by infinitation** [comment]
Seems that parent does this for the occurrence I need it in.

**Comment by dbr0** [comment]
Can we reopen this? Only first parent doesn't work for me.
Thanks!
