### ISSUE TITLE
maybe we need more simple guide

### ISSUE THREAD

**Issue by tomgets** [lazychaser/laravel-nestedset#149]
the main page is not include a guide content.
no install guide: for example : composer require "kalnoy/nestedset:~
no migration guide: should i have to migrate tables?
no config.php guide: should i config sth?

if we have those guide, i think the star will grow a lot.

**Comment by lazychaser** [comment]
There is an installation section in the docs which is as simple as possible

**Comment by tomgets** [comment]
i  found that in https://github.com/lazychaser/laravel-nestedset#requirements tks
