### ISSUE TITLE
Class 'Kalnoy\Nestedset\Nestedset' not found   

### ISSUE THREAD

**Issue by versantweb** [lazychaser/laravel-nestedset#150]
Hello,

thanks for your package. When installing on local it's OK. On linux server, when I migrate, I got this error : 

PHP Fatal error:  Class 'Kalnoy\Nestedset\Nestedset' not found in /home/clients/fcd4402c690c1a4c2f9b531cf9cb0825/new/database/migrations/2016_10_18_140712_create_miki_category_table.php on line 24

Here's my migration file content : 

`use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Kalnoy\Nestedset\Nestedset;

class CreateMikiCategoryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('miki_categories', function (Blueprint $table) {
            $table->engine = 'InnoDB';

            $table->increments('id');
            $table->string('class_name');

            $table->index('class_name');
            
            NestedSet::columns($table);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('miki_categories');
    }
}
`

What do you think is wrong ?

thanks a lot !

**Comment by versantweb** [comment]
Oh god, just passed 2 days on this problem before posting an issue. And 1 minutes later I found the problem.

It was : 

use Kalnoy\Nestedset\NestedSet;

instead of 

use Kalnoy\Nestedset\Nestedset;

the 'S' capital on NestedSet !!!

**Comment by lazychaser** [comment]
Ha-ha, that happens often =)

**Comment by jaypeegalang** [comment]
Got this error while migrating my schema, while i have successfully installed the package


 Method Illuminate\Database\Schema\Blueprint::nestedSet does not exist.

**Comment by leandrodiogenes** [comment]
@jaypeegalang make sure the NestedSetServiceProvider is active on your provider list.

**Comment by jaypeegalang** [comment]
thank you for your concern @leandrodiogenes , NestedSetServiceProvider already on list of provider, already fixed the problem
