### ISSUE TITLE
New Feature Drag & drop hierarchical

### ISSUE THREAD

**Issue by klaravel** [lazychaser/laravel-nestedset#152]
First of thank for making great plugin.

Is there any ways I can submit new sequence array and all category will re-sequence with that?

I want to use below plug in for sequence/sort data.
https://github.com/dbushell/Nestable
Demo: http://dbushell.github.io/Nestable/

All jQuery plugin just provide json or array object in return to save in database.

**Comment by lazychaser** [comment]
Hi.

[this](https://github.com/lazychaser/laravel-nestedset#rebuilding-a-tree-from-array) should work out

**Comment by klaravel** [comment]
Thank you for quick answered.

Is there anyway I can get idea about like `isLeaf()` node?

I want to build this structure and getting stuck with some if condition or something I am missing.

```html
<ol>
	<li>
		<div>Item 13</div>
	</li>
	<li>
		<div>Item 14</div>
	</li>
	<li>
		<div>With a switch</div>
		<ol>
			<li>
				<div>Item 16</div>
			</li>
			<li>
				<div>Item 17</div>
			</li>
			<li>
				<div>Item 18</div>
			</li>
		</ol>
	</li>
</ol>
```

I am using below code.

```php
$traverse = function ($categories, $prefix = '<ol>') use (&$traverse) {
	foreach ($categories as $category) {

		echo PHP_EOL.$prefix.'<li>'
			.'<div>'.$category->name.'</div></li>';

		$traverse($category->children, $prefix.'');

		echo '</ol>';
	}
};

$traverse($nodes);
```

**Comment by lazychaser** [comment]
You can use `getDescendantCount` function

**Comment by klaravel** [comment]
Great. I made my next step and I have array ready with ajax post and when I try to do rebuildTree it gave me error about "MassAssignmentException about id"

I know that error to make id to fillable but I don't want to do that. How can I sove this one without make id fillable.

**Comment by lazychaser** [comment]
MassAssignment means that neither fillable nor guarded arrays are set up

**Comment by klaravel** [comment]
@lazychaser 

Again Thanks for making great plugin. 

I found this one `baum` but they did not updated from last 1.5 years :(
