### ISSUE TITLE
root with descendants in Tree

### ISSUE THREAD

**Issue by M0H3N** [lazychaser/laravel-nestedset#154]
Hi
I want to build a tree (root and descendants  ) by this code : 
`$root = Category::where('sampleColumn',$value);
$tree = $root->descendants->toTree($root);`

but rendering  the tree  just shows  descendants  but I want to show the root also

**Comment by lazychaser** [comment]
You can either render the root separately or do this: `Category::descendantsOf($root)->push($root)->toTree();`
