### ISSUE TITLE
Question: What is best way to limit max depth for edit mode?

### ISSUE THREAD

**Issue by klaravel** [lazychaser/laravel-nestedset#156]
I have idea when we create category with make limitation for max depth level.

But when it's on edit mode how can I make validation or some kind of fix depth level.
So user don't make wrong tree.

Example:
Item A
- Sub Item A1
- - Sub Sub Item A11
Item B 
- Sub Item B1
- - Sub Sub Item B11
Item C
- Sub Item C1

In above example max depth level is 2. Item A should not go under of Item B.
But Item C can go only under Item A or Item B and should not go under rest of item so we can manage max depth level 2.

This screenshot is for my edit mode: http://screencast.com/t/TEGAJulJCTrI

Is there any easy way can I get each items total level of children like how we get depth level?

**Comment by klaravel** [comment]
I got one step for if I want to find for each individual.

`Page::withDepth()->descendantsOf(1)->pluck('depth')->unique()->count()`

How can I get this same result with each rows?

**Comment by lazychaser** [comment]
You can use depth. You could decline drop event for items with depth = 2
