### ISSUE TITLE
How do I get root ancestor

### ISSUE THREAD

**Issue by dbr0** [lazychaser/laravel-nestedset#159]
As in title.

I tried `root()` method but it isn't it.

**Comment by dbr0** [comment]
`$this->ancestors()->withDepth()->having('depth', '=', 0)->first()`

Do comment if it's inefficient or something. Cheers!

**Comment by lazychaser** [comment]
`$this->ancestors()->whereIsRoot()->first();`

**Comment by quantrung9** [comment]
@lazychaser You saved my day!
