### ISSUE TITLE
Filter tree

### ISSUE THREAD

**Issue by stigfaerch** [lazychaser/laravel-nestedset#161]
If I have a tree like this:
a
*aa
**aa1
**aa2
**aa3
*ab
**ab1
**ab2
b
*ba
**ba1
**ba2

Then I would like to get a filtered result of the tree by specific nodes. for example aa2 and ba2, which should leave me with:
a
*aa
**aa2
b
*ba
**ba2

Any idea how this could be done?

**Comment by lazychaser** [comment]
Basically, you need to filter out your nodes first, then load ancestors for every node, make a collection of ancestors with filtered nodes and finally convert it to tree.

Hardest part is to retreieve all ancestors of all filtered nodes. Ancestor `A` for node `B` is a node for which `B->lft` is between `A->lft + 1` and `B->rgt`. So, for every filtered node we need to add following condition:

```php
foreach ($nodes as $node) {
  $inner->orWhere('lft', '<', $node->getLft())->where('rgt', '>', $node->getLft());
}
```

Query for ancestors is schematically following:

```php
$ancestors = Category::query()
  ->whereNotIn('id', $nodes->modelKeys()) // exclude found nodes
  ->whereNested(function ($inner) use ($nodes) {
    foreach ($nodes as $node) {
      $inner->orWhere('lft', '<', $node->getLft())->where('rgt', '>', $node->getLft());
    }
  })
  ->get();
```

And to make a tree:

```php
$tree = $ancestors->merge($nodes)->toTree();
```

**Comment by stigfaerch** [comment]
Don't know which one is the most effective, but I also did this one:
```
$categoriesToShow = [20,22];

$traverse = function ($categories) use (&$traverse, $categoriesToShow) {
    foreach ($categories as &$category) {
        $children = count($category->children) ? ['children' => $traverse($category->children)] :[];
        $childFound = false;
        array_walk_recursive($children, function() use (&$childFound) { $childFound = true; });
        if(in_array($category->id, $categoriesToShow) || $childFound) {
            $tree[] = ['id' => $category->id, 'category_name' => $category->category_name] + $children;
        }
    }
    return isset($tree) ? $tree : [];
};

$tree = $traverse(Category::get()->toTree());
```
And don't ask me how it exactly works. I had an idea, but found it still worked when I remove some of the code, and then remove some more and ended up with this :-D
