### ISSUE TITLE
fixTree() throws exception Integrity constraint violation: 1048 Column 'slug' cannot be null.

### ISSUE THREAD

**Issue by AnjanishKumar** [lazychaser/laravel-nestedset#166]
**Backgroud** I have a existing table of categories with only `parent_id` information and other bunch of columns with foreign key relation. The goal is to convert the Category Modal to a nested set modal.

To solve this i am insert all the categories data from the older table to a new category table with `parent_id` and setting `_lft` and `_rgt` to `null`. After inserting all the data; i am fixing the tree by running `Category::fixTree()`  but the `fixTree` method throw exception.

```
  [Illuminate\Database\QueryException]

  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'slug' cannot be null (SQL: update `categories` set `_lft` = 1, `_rgt` = 2, `slug` = , `updated_at` = 2017-01-11 16:37:40 where `id` = 570)  


  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'slug' cannot be null
```
After looking at he exception message i am wondering why the `fixTree` is trying to set the column `slug` to `null`. The following method used in `fixTree` is returing the expected value.
```

getKeyName() returns id,
getParentIdName() returns parent_id,
getLftName() returns _lft,
getRgtName() returns _rgt,

```
**Workaround** `Category::rebuildTree([],false)` fixes the tree structure as expected.

I am not able to understand, why `fixTree()` is trying to set the `slug` columns to `null`?

**Comment by lazychaser** [comment]
`fixTree` loads nodes from db taking only few columns needed for the update. I'm sure that you're trying to set the slug each time the model is saved, but the column which slug generation depends on is missing, so `slug` becomes null.
