### ISSUE TITLE
compatible with laravel 5.4 

### ISSUE THREAD

**Issue by reno1979** [lazychaser/laravel-nestedset#167]
The nested package is really helping us out, thank you for writing it!

We want to update our laravel framework to 5.4, when do you expect compatibility with 5.4?

**Comment by lazychaser** [comment]
As soon as it released

**Comment by n1crack** [comment]
well, It is released. we are waiting for ^^

**Comment by lazychaser** [comment]
Well, composer cannot resolve stable 5.4 since `illuminate/container` is not stable yet so I can't test things.

**Comment by SeoFood** [comment]
fixed in https://github.com/lazychaser/laravel-nestedset/pull/171
