### ISSUE TITLE
How can I remove the parent node relationship without deleting then?

### ISSUE THREAD

**Issue by tiemiarashiro** [lazychaser/laravel-nestedset#169]
In my application I need remove only the relationship of two nodes. How can I do that?

**Comment by lazychaser** [comment]
I don't understand

**Comment by mgsmus** [comment]
Making a child node root (`$node->makeRoot()->save();`) removes parent-child relationship. Did you mean this?

**Comment by tiemiarashiro** [comment]
Exactly @mgsmus ! Thanks

**Comment by noda1** [comment]
@tiemiarashiro please close this issue
