### ISSUE TITLE
Maximum function nesting level error

### ISSUE THREAD

**Issue by legendarydrew** [lazychaser/laravel-nestedset#17]
Hello sir,
With the following code (regardless of what is inside the get()), I get a "Maximum function nesting level of '100' reached, aborting!" error:

```
$groups = ItemGroup::defaultOrder()->get(['name'])->toTree();
return $groups;
```

but this code works:

```
$groups = ItemGroup::defaultOrder()->get()->toTree();
return $groups;
```

The error appears to be a result of converting the tree to an array.

I've recenty updated Laravel to 4.2, and this issue also occurs with version 1.1. Perhaps I should stick with 4.1 for now?

**Comment by Silentscripter** [comment]
The fix you provided makes impossibile to call parent relationship in toArray() or toJson() methods.... is there any official workaround for this?
