### ISSUE TITLE
Incorrect order position in children property.

### ISSUE THREAD

**Issue by Shpartko** [lazychaser/laravel-nestedset#173]
Hello!
When I use _defaultOrder()_ after change positions (_Up()_ or _Down()_), all records show correct.

But, when I try get property $category->_children_, all elements sorting same, as created, without new positions.

Result:
http://joxi.ru/p271QBQcze5Jr7
Table:
http://joxi.ru/MAjJ4O4tQea5Ae

**Comment by lazychaser** [comment]
Hi, this is how it works. `defaultOrder` is entierly optional feature and I can't force it anywhere.
