### ISSUE TITLE
Help building a tree

### ISSUE THREAD

**Issue by enzonotario** [lazychaser/laravel-nestedset#174]
Hi!

First, I don't speak english, so please be gentle and prepare for gramatical horrors

I have implemented this package in an app that I'm building. It works fine, but now that I have my nested lists, I want that the user can search any item. I use transformers, and now I can do it by implementing something like  this:

For each item that I retrieve from the db doing a ```where($searchAttribute, 'like', '%'.$searchText.'%')```, I transform them and:
```
$ancestors = $item->getAncestors()->toTree()->toArray();
$ancestors = $this->transformAncestors($ancestors);
$output['meta']['ancestors']['data'] = $ancestors;
```

```
public function transformAncestors(array $ancestors) {
    foreach ($ancestors as $index => $ancestor) {
        $ancestors[$index] = $this->transformAncestor($ancestor);
    }

    return $ancestors;
}
```

```
public function transformAncestor(array $ancestor) {
    $ancestor = array_only($ancestor, [
        'id',
        'name',
        'parent_id',
        'children'
    ]);

    if (! empty($ancestor['children'])) {
        $ancestor['children'] = $this->transformAncestors($ancestor['children']);
    } else {
        $ancestor['children'] = [
            [
                'data' => $this->item
            ],
        ];
    }

    $output = [
        'data' => [
            'id' => $ancestor['id'],
            'attributes' => array_only($ancestor, ['name', 'parent_id']),
            'relationships' => [
                'children' => [
                    'data' => $ancestor['children']
                ]
            ]
        ],
    ];

    return $output;
}
```

It works fine!, then in Angular I show the tree and looks good. But I have a problem.
If I have the next tree:
```
- asd
    - qwe
        -asd
```

Well, if the user searches for ```asd```, the ```where()``` retrieve me two results, they transform as Collection first, that transform each Item and transform its ancestor as I show previous. So, in angular, I show 2 trees:
```
- asd
---------------------
- asd
    - qwe
        -asd
```
I want to merge the results and don't know how to do it. Consider that the tree can be as:
```
- asd
    - qwe
        - cvb
            - asd
    - zxc
        - asd
    - asd
```

Can you help me please?

Thanks so much!

**Comment by lazychaser** [comment]
Hi! see #161
