### ISSUE TITLE
How to rebuild a tree starting from a node

### ISSUE THREAD

**Issue by mbouclas** [lazychaser/laravel-nestedset#177]
I need to rebuild the tree starting from a specific node. My tree has multiple root nodes and the user can reorder their children. Calling the rebuild method when passing the children of a root node as argument, flattens the entire tree.

**Comment by lazychaser** [comment]
Consider to use scoping for distinguishing different trees.

**Comment by mbouclas** [comment]
So this is what happens when i try this out. To be clear, the UI posts only the child tree of the root node, not the root node including the children. So, there are 2 things i tried with scoped.

1) `$model->scoped(['table_id' => $table_id])->rebuildTree($request->all());` where table_id is the same on the root and child nodes. In this case, the tree is simply flattened. All the posted child nodes become root nodes.

2) Find the parent, attach the posted children and then rebuild the tree the same way. so, 
`$parent = $model->find($parentId)->toArray();` 

then 
`$parent['children'] = $request->all();`

finally 
`$model->scoped(['table_id' => $table_id])->rebuildTree($parent)`

In this case i get an error,
`ErrorException in Arr.php line 123:
array_key_exists() expects parameter 2 to be array, integer given`

any ideas?

**Comment by lazychaser** [comment]
`rebuildTree` accepts an array of nodes https://github.com/lazychaser/laravel-nestedset#rebuilding-a-tree-from-array

**Comment by mbouclas** [comment]
this is what i'm posting. $request->all() is basically an array representation of the children of a certain node after the user has done moving stuff around. 
For example 
```
Array
(
    [0] => Array
        (
            [id] => 39
            [title] => Sony
            [created_at] => 2017-02-20 10:25:32
            [updated_at] => 2017-02-20 10:25:32
            [_lft] => 2
            [_rgt] => 3
            [parent_id] => 31
            [table_id] => 31
            [children] => Array
                (
                )

        )

)
```

This is a node that belongs to a root with id 31. Both the root and the children have table_id set to 31. If i just run the scoped rebuild passing the above array as argument ($request->all()) like so `$model->scoped(['table_id' => $table_id])->rebuildTree($request->all())` what happens is that the child node becomes root and the tree is reformed as so :

- The root node's lft, rgt change from 1,2 to 3,4
- The child's lft,rgt change from 2,3 to 1,2 and the parent_id becomes null

**Comment by mbouclas** [comment]
Ok, i figured it out. For anyone that may have the same problem, the solution is to pass the entire scoped tree in the rebuild and not just the children. So in my case, I had to grab the parent first, attach the posted children to it and then rebuild
```
        $parent = $model->find($parentId)->toArray();

        $parent['children'] = $request->all();

        $model->scoped(['table_id' => $parentId])
            ->rebuildTree([$parent]);
```

Notice that we have to post an array instead the `$parent` which what i was doing wrong all along.

@lazychaser Thank you for your help and work on this project

**Comment by sunil-uam** [comment]
Does it delete the existing nodes as well?
