### ISSUE TITLE
where is breadcrumb option, how i can retrieve parents of child

### ISSUE THREAD

**Issue by knour89** [lazychaser/laravel-nestedset#179]
hello i want to inverse the hierarchy, since each child can have one parent, how i can retrieve the breadcrumb (parents) of a child?

-Electornic
--Computer and tablet
---Computer  **(want get parent of computer as below)**

i want below
Compiter > Computers and Tablets > Electronic

**Comment by lazychaser** [comment]
`$node->getAncestors()`
