### ISSUE TITLE
i want to retrive the hierarchy in ul>li & table format

### ISSUE THREAD

**Issue by knour89** [lazychaser/laravel-nestedset#182]
i want to retrive the hierarchy in ul>li & table format and cant do it, please help

<ul>
<li>machine
<ul>
<li>car</li>
</ul>
</li>
<ul>

# | name| option

1|machine|edit
2|-car|edit

**Comment by lazychaser** [comment]
You can do this using recursive function/template. Basic example in the docs: https://github.com/lazychaser/laravel-nestedset#building-a-tree

**Comment by InToSSH** [comment]
When I was building an eshop, I needed exactly this, and I ended up using this:
[https://github.com/lavary/laravel-menu](laravel-menu) 
I am feeding data from Nestedset to this Menu, advantage is that you can easily set active item, and the menu is shared through all views. And of course it has ul>li output out of the box.
