### ISSUE TITLE
Get siblings with related model in a single query

### ISSUE THREAD

**Issue by dbr0** [lazychaser/laravel-nestedset#183]
Hi, I would like to load siblings with some of related models.

For now, I'm doing it this way:

    $element->getSiblings()->load('first_relation','second_relation');

I suppose this runs two queries, first one to get siblings, and the next one to get relations.
Is there a way to do it in a single go?

Something like:

    $element->getSiblingsWithRelations('first_relation','second_relation');

Thanks!

**Comment by lazychaser** [comment]
This will do 3 queries. One for getting siblings and two for loading relations. This is the way it works. You can write a custom query where you would join tables, but this is almost the same as making three queries.

**Comment by dbr0** [comment]
Thanks for the clarification!
