### ISSUE TITLE
Hiding restricted nodes in the tree

### ISSUE THREAD

**Issue by marvinschroeder** [lazychaser/laravel-nestedset#187]
I would like to get multiple specific nodes from the tree including all descendants, but not up to the root. I tried the following eager loading descendants, but the toTree() method is not returning all nodes.

Example tree:

- Root Nr. 1
-- Subnode Nr. 1.1
-- Subnode Nr. 1.2
- Root Nr. 2
-- Subnode Nr. 2.1
-- Subnode Nr. 2.2
--- Subnode Nr. 2.2.1
- Root Nr. 3 
-- Subnode Nr. 3.1

Now i would like to build the tree with the following nodes as "roots": "Subnode Nr. 2.2" and "Root Nr. 3" and their descendants. Think of it like "the User has only permission to view specific nodes". The tree should look like:

- Subnode Nr. 2.2
-- Subnode Nr. 2.2.1
- Root Nr. 3 
-- Subnode Nr. 3.1

This is not working:

``
$nodes = Node::whereIn('id', $ids)->with('descendants')->get()->toTree();
``

Another approach: Selecting the specific nodes and then iterating over them, to select all descendants in one single query is working, but when i use toTree() the node "Root Nr. 3" is removed. 

```
$nodes = Node::whereIn('id', $ids)->get();

$nodeQuery = Node::query();
foreach ($nodes as $node) {
                $nodeQuery->orWhere(function($query) use ($node){
                    return $query->whereBetween('_lft', [$node->_lft, $node->_rgt]);
                });
}
$nodesTree = $nodeQuery->with('relationData')->defaultOrder()->get()->toTree();
```
 
I think it relates to the method toTree() which removes the root node from tree and because here is no root node, it will remove the lowest found node, which is the root node "Root Nr. 3". When i change to tree structure to have a super-root node for all "Root Nr. X" it is also not working.

**Comment by lazychaser** [comment]
I suggest following: select whole tree, `hide` not allowed nodes, if hidden node has visible descendants, make it visible (you can disable it, change name, pull descendants up).
