### ISSUE TITLE
Returning Lowest Descendants of all roots

### ISSUE THREAD

**Issue by cwcrawley** [lazychaser/laravel-nestedset#191]
I have the following structure:

```
Root 1
- Child 1.1
- Child 1.2
- - Grand Child 1.2.1
Root 2
- Child 2.1
- - Grand Child 2.2.1
- Child 2.2
- Child 2.3
- - Grand Child 2.2.3
```

How do I get all the lowest level descendants from all the nodes? i.e. I want all the descendants where they don't have any descendants.

Since the lowest descendant could be on Depth 1 or Depth 2 (or conceivably Depth 3) - I don't think I can use `withDepth()`. 

What would be the recommended way of accomplishing this?

**Comment by lazychaser** [comment]
Add following condition to the query: `whereRaw('_rgt = _lft + 1')`

**Comment by cwcrawley** [comment]
Sorry - Which query?

**Comment by lazychaser** [comment]
Yep, `Category::whereRaw('_rgt = _left + 1')->get();`

**Comment by lazychaser** [comment]
In 4.2.3 added `leaves()` method: `Category::leaves()`
