### ISSUE TITLE
Ancestor(s) and Self Node

### ISSUE THREAD

**Issue by rishabgarg** [lazychaser/laravel-nestedset#193]
In my database I store the child category id and I need to get parent category along with the child record.

Is there a way to get the current node and its ancestors? 

Category::ancestorsOf($id) gives me the ancestors but excludes this($id) node.

**Comment by murilozilli** [comment]
Have you tried `$node->ancestors()->get();`

**Comment by rishabgarg** [comment]
Yes. It just returns the parent nodes.

**Comment by lazychaser** [comment]
In 4.2.3 added `ancestorsAndSelf` method

**Comment by JeanLucEsser** [comment]
Could it be possible to have the ancestorsAndSelf method behave like ancestors, that is being able to do `$node->ancestorsAndSelf()->get();` and most importantly being able to eager load `with('ancestorsAndSelf')`? For the sake of uniformity, same could be available to descendants.

**Comment by lazychaser** [comment]
@JeanLucEsser `Category::ancestorsAndSelf($id)`

**Comment by JeanLucEsser** [comment]
Yes I'm fully aware of that, but how can I use it to eager load as in `with('ancestorsAndSelf')`?

**Comment by it-can** [comment]
yeah eager loading would be very nice with  ```ancestorsAndSelf``` function

**Comment by mohammedabdallah** [comment]
Did Eagering this relation ancestorsAndSelf worked with u ?
