### ISSUE TITLE
Not null violation

### ISSUE THREAD

**Issue by fearrr** [lazychaser/laravel-nestedset#195]
Laravel 5.4
PosgreSQL 9.6

Использую генератор в миграции
`NestedSet::columns($table);`

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "_lft" violates not-null constraint

Почему не сделать поля '_lft', '_rgt' nullable?
 `$table->unsignedInteger(self::LFT)->nullable();`
 `$table->unsignedInteger(self::RGT)->nullable();`

**Comment by lazychaser** [comment]
В 4.2.3 сделал по-умолчанию нулевыми.
