### ISSUE TITLE
Rebuild tree based on a scope

### ISSUE THREAD

**Issue by murilozilli** [lazychaser/laravel-nestedset#196]
Is it possible to rebuild a tree based on a scope? Imagining the `Menu` and `MenuItem` association presented in the Scope documentation. Rebuilding the tree from a given `menu_id` scope.

**Comment by murilozilli** [comment]
Just saw it is already built that way.

**Comment by murilozilli** [comment]
Actually if the model uses softdelete it is ignoring the scope attribute.

**Comment by lazychaser** [comment]
First of all, you need to do following: `Category::scoped($attributes)->rebuildTree($data)`
But in this case new nodes will not get updates unless data contains needed attributes. This is a bug.

**Comment by murilozilli** [comment]
I'll try that. Thanks for the help.

Anyway, isn`t it weird that if the model uses softdelete you have to to like you said but if it doesn`t it is hardcoded to use scoped query?

**Comment by lazychaser** [comment]
`newScopedQuery` returns default query if model doesn't use scoping. In the code above deletes models that aren't in provided data unless `SoftDeletes` is used
