### ISSUE TITLE
get all row in the last level of tree

### ISSUE THREAD

**Issue by AbdullahGhanem** [lazychaser/laravel-nestedset#197]
i have 2 root 
like this 
![screenshot from 2017-04-11 13 07 54](https://cloud.githubusercontent.com/assets/5055892/24906768/75309ffe-1eb9-11e7-98ad-ad25c52c4ee8.png)
how get the last children level of root1 (id:1) + root2 (id:4)?
to get row 3 and row 5

**Comment by lazychaser** [comment]
`Category::leaves()`

**Comment by AbdullahGhanem** [comment]
Thank You Alexander

**Comment by lazychaser** [comment]
This one was added couple days ago

**Comment by AbdullahGhanem** [comment]
nice package alexander go ahead
