### ISSUE TITLE
How to recognize a nested change?

### ISSUE THREAD

**Issue by reno1979** [lazychaser/laravel-nestedset#198]
Our category tables have a column which hold the complete path to that category. 

On changes to that category, this path should be recreated. 

So if we move a nested category up or down (etc) the path for this category should be changed. 

How can I detect a nested change?

**Comment by lazychaser** [comment]
```
if ($node->save()) {
    $moved = $node->hasMoved();
}
```

**Comment by reno1979** [comment]
@lazychaser 

Thank you, I will update our observer to look for that condition on save events.
