### ISSUE TITLE
Question - order by category names

### ISSUE THREAD

**Issue by cardi777** [lazychaser/laravel-nestedset#201]
Hi, love it! but i can't my list to order by the category name - column is "page_name"

Can you give any examples of how that is done?

**Comment by lazychaser** [comment]
`Category::orderBy('page_name')`?

**Comment by cardi777** [comment]
Thanx for your response - pulling my hair out :) i should have said im considering the tree structure

That'll order by the cat name only regardless of the structure. Orders by tree structure is more like what im trying to do I supose

**Comment by lazychaser** [comment]
You can convert it to tree after that. `toTree` or `toFlatTree`

**Comment by cardi777** [comment]
tis an awsome feature. I ended up saving the category tree into a seperate column for each category so i can more easily order the cats
