### ISSUE TITLE
ancestorsAndSelf() / getAncestorsAndSelf()

### ISSUE THREAD

**Issue by OlesKashchenko** [lazychaser/laravel-nestedset#202]
Hello!

Could You implement such methods as:
**ancestorsAndSelf()** / **getAncestorsAndSelf()**
as You've already implement with node descendants ?

It will be very useful!

Thank's

**Comment by lazychaser** [comment]
Those are already in there. Update the package.

**Comment by OlesKashchenko** [comment]
Call to undefined method Illuminate\Database\Query\Builder::getAncestorsAndSelf()

Missing argument 1 for Kalnoy\Nestedset\QueryBuilder::ancestorsAndSelf()

v. 4.2.4

**Comment by OlesKashchenko** [comment]
Got it!

I called **ancestorsAndSelf()** on entity, not statically.
