### ISSUE TITLE
Moving children before deleting their parent

### ISSUE THREAD

**Issue by insight-media** [lazychaser/laravel-nestedset#205]
When i delete a node, i want to retain the children of that node by moving them to their parents' level.

I have a 'deleting' event as follows:

                $parent->children->each(function ($child) use ($parent) {
                    $child->parent_id = $parent->parent_id;

                    // notice this part
                    $internal_name = $child->internal_name;
                    $child->internal_name = '';
                    $child->save();
                    $child->internal_name = $internal_name;

                    $child->save();
                });

When i only set the parent_id, it doesn't get updated.
When i also set another property, parent_id does get updated.

Even when the parent_id gets updated and the child node moves, right before deleting the parent. The moved child does get deleted as well.

I don't get it :)

**Comment by lazychaser** [comment]
What is that about `internal_name`?

**Comment by insight-media** [comment]
When i only change the parent_id property and save(), that property doesn't get updated.
When i change the parent_id AND another random property, the model gets saved as it should.

**Comment by lazychaser** [comment]
Which version are you using?

**Comment by insight-media** [comment]
4.1 on Laravel 5.4
PHP 7.1

**Comment by insight-media** [comment]
I solved this by overriding the bootNodeTrait method and removing the 'deleted' event.

        static::deleted(function ($model) {
            $model->deleteDescendants();
        });
