### ISSUE TITLE
 Move children and their father, how do i do, help me.

### ISSUE THREAD

**Issue by luisfevaleriano** [lazychaser/laravel-nestedset#209]
![move](https://cloud.githubusercontent.com/assets/5165935/25571979/b4ad7e6c-2dfb-11e7-91fe-d5714317cd64.PNG)

**Comment by InToSSH** [comment]
Just fetch your "father" (parent node), and use one of these:
```
// #1 Using deferred insert
$node->appendToNode($parent)->save();

// #2 Using parent node
$parent->appendNode($node);
```
If you move the parent to somewhere else, or make it child of another parent, the rest of the children inside the parent you are moving will follow.

**Comment by Insua** [comment]
wonderful,it's the best way to handle tree!
