### ISSUE TITLE
Limit children returned per depth

### ISSUE THREAD

**Issue by user651896** [lazychaser/laravel-nestedset#213]
Is it possible to limit the number of children returned per depth?

For example:

- Return 5 children at depth 0
- Return 3 children at depth 1
- Return 2 children at depth 2

Thanks.

**Comment by lazychaser** [comment]
There is no simple way of doing this. You can select all nodes and then filter out unneeded. If they are heavy, you can select tree-related nodes with identifiers, filter out and then load needed data by primary keys.

**Comment by user651896** [comment]
Can you explain a little further what you mean by your second method ("If they are heavy, you can select tree-related nodes with identifiers, filter out and then load needed data by primary keys.")?

**Comment by lazychaser** [comment]
```php
$nodes = Category::get([ 'id', '_lft', '_rgt', 'parent_id' ])->toFlatTree();
$nodes = filterNodes($nodes);
$nodes = Category::whereIn('id', $nodes->modelKeys())->get()->toTree();
```
