### ISSUE TITLE
Prepend to node in another scope

### ISSUE THREAD

**Issue by insight-media** [lazychaser/laravel-nestedset#214]
I'm getting a headache over this issue:

| id 	| navigation_id 	| _lft 	| _rgt 	| parent_id 	
|----	|--------------- 	|------	|------	|-----------	
| 1  	| 1             	        | 1    	| 2    	| null      	
| 2  	| 1             	        | 3    	| 4    	| null      	
| 3  	| 2             	        | 1    	| 2    	| null      	
| 4  	| 2             	        | 3    	| 4    	| null      	

I want id 2 to be a child of id 4.
If they were in the same scope (navigation_id), there would be no problem.

     $parent = $this->page->find($parent_id); // results in model id 4
     $parent->prependNode($page); // $page of course being model id 2

This gives me 'Cannot move node into itself.'

**Comment by lazychaser** [comment]
There is no means to move nodes from scope to scope. Can't you simply duplicate a node?

**Comment by insight-media** [comment]
Duplication is possible. Although it's somewhat of a hassle.
The scoping feature is available, so i assume i'm not the only one that might need to move nodes between scopes. :-)

**Comment by lazychaser** [comment]
Scoping is made to distinguish trees. If you need to move nodes from one scope to another, consider to use multiple root nodes instead of scoping.
