### ISSUE TITLE
Error when eager loading

### ISSUE THREAD

**Issue by it-can** [lazychaser/laravel-nestedset#216]
I get this error on Laravel 5.4 when calling this piece of code:

```
Category::with('ancestors')->paginate(30);
```

```
Call to undefined method Illuminate\Database\Query\Builder::addEagerConstraints()
```

This works correctly though:
```
Category::with('descendants')->paginate(30);
```

Any idea what's wrong?

**Comment by lazychaser** [comment]
@ralphschindler any idea?

**Comment by lazychaser** [comment]
Should work in v4.2.5

**Comment by it-can** [comment]
That was quick, thanks will test later today!

**Comment by it-can** [comment]
Works perfect! Thanks!

**Comment by pls-kick-me** [comment]
Doesn't work with siblings now:
`
$category->load(['siblings']);
`
Gives me: Call to undefined method Kalnoy\Nestedset\QueryBuilder::addEagerConstraints()

Version 4.3.4

**Comment by howdu** [comment]
@lazychaser is there a way to make siblings work with eager loading too?

**Comment by AforDesign** [comment]
Facing the same issue here. Version 6.0.2.
Laravel version 8.83.27
