### ISSUE TITLE
Correct value for root node's left and right

### ISSUE THREAD

**Issue by newbro** [lazychaser/laravel-nestedset#220]
Sorry I'm a bit confused regarding the left and right value for a nested set. I have inserted 3 nodes with the same codes stated in the documentation:
```
$node = Category::create([
    'name' => 'Foo',
    'code' => 'root',

    'children' => [
        [
            'name' => 'Bar',
            'code' => '1',

            'children' => [
                [ 'name' => 'Baz', 'code' => '2' ],
            ],
        ],
    ],
]);
```
The left and right value for the root node is 1 and 2 respectively, but shouldn't it be 1 and 6 consider it has 2 descendants? Or did I somehow setup the model incorrectly?

**Comment by lazychaser** [comment]
Are you looking in the database for lft and rgt values after inserting models?

**Comment by newbro** [comment]
Yes I was referring to the value stored in table, left and right values are 1 and 2 for the root node, 2 and 3 for the 2nd node, 3 and 4 for the 3rd node. The parent_id are null, 1 and 2 which I assume are correct.

**Comment by newbro** [comment]
OK it was my bad, somehow I used getScopeAttributes by mistake which seems to affect how the tree was created.
