### ISSUE TITLE
Cannot eager load parent when NodeTrait is used in Model.

### ISSUE THREAD

**Issue by ad1199** [lazychaser/laravel-nestedset#222]
Cannot eager load parent when NodeTrait is used in Model.
E.g.
I have a model category as shown below:
class Category extends Model{

   use NodeTrait;
   .....

}

Now when I eager load the parent,

$categories = Categories::with( 'parent' )->paginate( 5 );

Parent property won't show in result.

When I remove NodeTrait from category model it works.

**Comment by lazychaser** [comment]
I'm sure you're looking at a result of `toArray`? `parent` is excluded from there since it would fall into infinite recursion.

**Comment by ad1199** [comment]
Actually, I want to return a json response with all the categories with its parent category ( but not parent of parent ). But the parent relation won't show up in the response.

**Comment by lazychaser** [comment]
`return Category::get()->toTree();`

**Comment by stian-scholtz** [comment]
Hi @lazychaser 

How are we supposed to eager load the parent in the cases that we don't want to use the tree? Excluding it from the result when using toArray() does not make sense. I understand it would cause infinite recursion if the parent also contains children with parents etc. Doesn't it make more sense to exclude the parent.children attributes instead?
