### ISSUE TITLE
Problem with NodeTrait

### ISSUE THREAD

**Issue by BorisPobeshymov** [lazychaser/laravel-nestedset#223]
laravel 5.4, "kalnoy/nestedset": "^4.2", php 7.0
have a problem when implemend to model

use Kalnoy\Nestedset\NodeTrait;
class CatalogCategory extends Model
{
    use NodeTrait;

}

Error: Trait 'Kalnoy\Nestedset\NodeTrait' not found

how can I fix this?

**Comment by lazychaser** [comment]
Maybe `composer dump-autoload`?

**Comment by BorisPobeshymov** [comment]
This was a problem with the remote server
