### ISSUE TITLE
Trait method replicate has not been applied

### ISSUE THREAD

**Issue by it-can** [lazychaser/laravel-nestedset#227]
I am getting this error since commit #217 

https://github.com/lazychaser/laravel-nestedset/commit/e6ab99fe457859a66bafa993d60f050ee11ded67

```
Trait method replicate has not been applied, because there are collisions with other trait methods on App\Models\Category
```

I also use this package:
https://github.com/cviebrock/eloquent-sluggable

**Comment by lazychaser** [comment]
I guess some other traits use this method and you'll have to resolve the collision manually

**Comment by it-can** [comment]
I also use this package: https://github.com/cviebrock/eloquent-sluggable

**Comment by it-can** [comment]
Do you have any tips on resolving this? I need to use both packages

**Comment by lazychaser** [comment]
http://fi2.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict

**Comment by gotrecillo** [comment]
If u call both replicate methods u will end with three objects instead of two. U have to manually overwrite replicate method.

```
use Cviebrock\EloquentSluggable\Services\SlugService;
use Sluggable , NodeTrait {
    NodeTrait::replicate as replicateNode;
    Sluggable::replicate as replicateSlug;
}

public function replicate(array $except = null)
{
    $instance = $this->replicateNode($except);
    (new SlugService())->slug($instance, true);

    return $instance;
}
```

**Comment by jordanade** [comment]
@gotrecillo , I tried your code in my Page model but when doing a Page::fixTree(), the following error was returned:
`Illuminate\Database\QueryException with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'slug' cannot be null (SQL: update `pages` set `_lft` = 2, `_rgt` = 3, `slug` = , `updated_at` = 2018-01-02 00:23:59 where `id` = 2)'`

Also, nestedset doesn't work. Upon insert, the other rows never get updated.
Any ideas?

**Comment by Majid-Kamali** [comment]
`
 use Sluggable, NodeTrait {
        NodeTrait::replicate as replicateNode;
        Sluggable::replicate as replicateSlug;
    }

    public function replicate(array $except = null)
    {
        $instance = $this->replicateNode($except);
        (new SlugService())->slug($instance, true);

        return $instance;
    }
`

after that use

`
public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
`
