### ISSUE TITLE
ancestorsAndSelf sort issue

### ISSUE THREAD

**Issue by it-can** [lazychaser/laravel-nestedset#232]
I am retrieving items with the ```ancestorsAndSelf``` function like this:

```
$data = Category::ancestorsAndSelf($category_id);
```

This works, but sometimes the data is not sorted the way I expect it to be.

What I expect:

```
1. Main category (ID = 1)
2. Subcategory 1  (ID = 135)
3. Subcategory 2 (ID = 13)
```
what I get is this:

```
1. Main category (ID = 1)
2. Subcategory 2  (ID = 135)
3. Subcategory 1  (ID = 13)
```

It seems to be sorting on the ID field?

**Comment by lazychaser** [comment]
`Category::defaultOrder()->ancestorsAndSelf($category_id)`

**Comment by it-can** [comment]
Thanks!
