### ISSUE TITLE
Delete Many-To-Many Relationship to other Models

### ISSUE THREAD

**Issue by johannesschobel** [lazychaser/laravel-nestedset#235]
Hey @lazychaser and community,

thank you very much for this awesome package. I stumbled upon it and I really like it!
When working with the package, I stumbled upon a "problem".

Consider the following example:
I have a `Category`-tree (build with your package). Each `Category` can have many `Product`s, every `Product` can belong to many `Categories`. Both models have the respective relationship methods correctly set up; the pivot table is also correctly defined and migrated!

Now, if i update the tree using the `rebuildTree` function, all entries in the pivot-table should be "updated" accordingly. That means, that, if the `Category` was deleted during the `rebuildTree()` method, respective entries for these `Product`s should be deleted as well. How can I achieve this?!

Cheers

**Comment by lazychaser** [comment]
Set up foreign keys on database

**Comment by johannesschobel** [comment]
I did, but i use `SoftDeletes` - therefore, `DELETE` statements are not sent to the DB

**Comment by lazychaser** [comment]
Well, you should listen on `deleted` event and delete products manually
