### ISSUE TITLE
Using withDepth() with 30000 nodes in table slow.

### ISSUE THREAD

**Issue by dcanaud** [lazychaser/laravel-nestedset#237]
Is there any way to get the depth more efficiently in a table with 30000 records? Currently when I query the database and include the depth, it is taking too long.

**Comment by thomasdominic** [comment]
The depth could be stored in the database.

**Comment by dcanaud** [comment]
Do you have any suggestions on how to compute the depth?

**Comment by lazychaser** [comment]
As @thomasdominic said, the depth can be stored in the database

**Comment by thomasdominic** [comment]
It's a bit more consumer at insertion, but so much better for selection.
Before I used etrepat/baum but it is no longer maintained, and in this package the depth was stored in base. In my view, it must be recalculated and saved with each insert or move.

If you look etrepat/baum you may be inspired. 
https://github.com/etrepat/baum/blob/master/src/Baum/Node.php#L1076

**Comment by nivv** [comment]
@thomasdominic did you find a way to implement this?
