### ISSUE TITLE
toTree() strange behaviour

### ISSUE THREAD

**Issue by tachyon-ops** [lazychaser/laravel-nestedset#244]
Hi there, I'm trying to get a tree from my Page model:
$tree = Page::where('published_at', '<', Carbon::now())->reversed()->get()->toTree();

However, the tree is currently like this:
id_1 (published before now)
   |-> id_2 (published before now)
   |-> id_4 (published before now)
id_3 (published before now)
id_5 (not yet published)
   |-> id_6 (published before now)
   |-> id_7 (not yet published)

My tree only get's id_6... and it should not get the branch steaming from id_5. Besides, id_1 and id_5 aren't appearing, as well as their children. Anyone has a thought?

**Comment by lazychaser** [comment]
Look at the results without `toTree` first.

**Comment by tachyon-ops** [comment]
Without toTree it gives me a proper un-ordered collection. I went through with my own implementation of a method to generate a tree from all published root items if there are children and recursively call that method to populate results to a certain depth on each item.

I'll close now.
