### ISSUE TITLE
Deleting a child entity not updating parent lft and rgt values

### ISSUE THREAD

**Issue by booshmightythe** [lazychaser/laravel-nestedset#245]
When i delete a child entity of a parent that only has 1 child, it removes the child fine but it does not update the parent lft and rgt values. I am on version 3 at the moment as we are using laravel 5.1. This is when using softdeletes.

Any ideas? Many thanks

**Comment by lazychaser** [comment]
If you use softdeletes, nodes's `deleted_at` timestamp is updated only, the node stays there so no need to update parent.
