### ISSUE TITLE
i want by other filed order?

### ISSUE THREAD

**Issue by seth-shi** [lazychaser/laravel-nestedset#249]
In my website, the classification of goods can be clicked sort, what should I do to sort first according to `defaultOrder`?,
And then sort it by `order_lv`. I'm trying to use `Category::defaultOrder()->orderBy('order_lv', 'asc')->withDepth()->get();` there's no effect

**Comment by lazychaser** [comment]
Don't use `defaultOrder`

**Comment by seth-shi** [comment]
How can I, according to the`defaultOrder`=>`parent_id` group order, then according to the sequence of the `order_lv`custom field

**Comment by lazychaser** [comment]
Maybe this'll help https://github.com/lazychaser/laravel-nestedset#building-flat-tree
