### ISSUE TITLE
Eager loading of ancestors not working when using scope

### ISSUE THREAD

**Issue by harrisnl** [lazychaser/laravel-nestedset#250]
Eager loading of ancestors when working in scoped mode is not working, wrong ancestors (of other scopes) are attached to a node. Please let me know if you need more information to reproduce this.

**Comment by lazychaser** [comment]
Ancestors retrieval in scoped mode is tested. I need your query and the data that it gets

**Comment by zek** [comment]
I got same issue

**Comment by shanjiechen** [comment]
I got same issue
