### ISSUE TITLE
when I search by id Why does not depth start from 0?

### ISSUE THREAD

**Issue by sensugaz** [lazychaser/laravel-nestedset#251]
This is data

Id	name	left	right		parent_id
1	A		1	10		null	
2	B		2	9		1
3	C		3	6		2
4	D		4	5		3
5	E		7	8		2

This is command 
`Demo::withDepth()->descendantsOf(2);`

{
	id: 3,
	name: “C”,
	depth: “2”
},
{
	id: 4,
	name: “D”,
	depth: “3”
},
{
	id: 5,
	name: “E”,
	depth: “2”
}

when I search id = 2 Why does not depth start from 0?

I want  this result.
{
	id: 3,
	name: “C”,
	depth: “1”
},
{
	id: 4,
	name: “D”,
	depth: “2”
},
{
	id: 5,
	name: “E”,
	depth: “3”
}

**Comment by lazychaser** [comment]
Because depth = number of ancestors
