### ISSUE TITLE
About filtering nested atributes...

### ISSUE THREAD

**Issue by SarajevoNo1** [lazychaser/laravel-nestedset#254]
Hi 

I just working on this tutorial: https://www.codecourse.com/lessons/build-a-classified-ads-site

And they use nested sets for categories and locations ... in this classified tutorials... my question is Can I implement advanced custom search filters to be related to that nested sets attributes (categories) ... you know... like for cars it will be number of doors, and the power engine for real estate it will be year of builth and number of rooms... etc.. ?!

And how can I do that what else I need to use ... To be visible when posting ads and when searching.... 

Thanks

**Comment by lazychaser** [comment]
https://github.com/lazychaser/laravel-nestedset#getting-related-models-from-other-table
