### ISSUE TITLE
When Appending a Node - LogicException Node must exists. (in NodeTrait.php (line 1181))

### ISSUE THREAD

**Issue by FilipQL** [lazychaser/laravel-nestedset#255]
Hi,

After updating to **v4.3.1** - when I try to append a node using the parent attribute:

```
        $category = new ArticleCategory();
        $category->parent_id = 2;
```

... I am getting the following error:

`(1/1) LogicException Node must exists. in NodeTrait.php (line 1181) ...`

![mozilla firefox 2018-01-05 23 48 01](https://user-images.githubusercontent.com/18264428/34631901-f246940c-f272-11e7-8ffb-1358212a6824.png)

I am using Laravel 5.4

**Comment by FilipQL** [comment]
Ok, this has nothing to do with the version... it's related to the article https://habrahabr.ru/post/279233/  - this part is making trouble:

```
    protected static function boot()
    {
        static::saving(function (self $model) {
            if ($model->isDirty('slug', 'parent_id')) {
                $model->generatePath();
            }
        });

        static::saved(function (self $model) {
            static $updating = false;

            if (! $updating && $model->isDirty('path')) {
                $updating = true;

                $model->updateDescendantsPaths();

                $updating = false;
            }
        });
    }
```
It seems that `parent::boot();` is missing.

**Comment by mackhankins** [comment]
@FilipQL did you solve this with `parent::boot():`?  I can't seem to get it to work.

Update: I solved it sort of.  I'm migrating a bunch of data and when I create my roots with the boot method on the model it saves lft rgt as 0 which causes the error.  I'll sort it.

**Comment by ElaheSoleimani** [comment]
run
`Node::fixTree()`
fix for me

**Comment by mewcrow** [comment]
> run
> `Node::fixTree()`
> fix for me

`<Model>::fixTree()` worked for me
`Page::fixTree()` in my case
