### ISSUE TITLE
[Doubt] - A Tournament Struct

### ISSUE THREAD

**Issue by regiszanandrea** [lazychaser/laravel-nestedset#256]
Hi, 

I have a doubt about a Tournament structure, in initial I don't have a root node, it's a Inverse Tree. How can I create the tree using the laravel-nestedset package? 

Thanks.

**Comment by lazychaser** [comment]
You should store teams in separate table. Initialize tournament tree based on the number of teams. So if there are 4 teams, then there will be 3 levels with one node at the top (finalist), two nodes on the second level and 4 on the last one. Each node references a team and has at most two children. Each node is a match. Leaves are initial teams at the last level.

**Comment by regiszanandrea** [comment]
Thanks lazychaser for the feedback, I didn't understand just this:
`"Each node references a team..."`

My table Matches has the following columns:

id - integer
nestedset (laravel-nestedset)
team_a - foreign key to table Teams
team_b - foreign key to table Teams
winner - foreign key to table Teams

So, each node is a match, than I have two team per each match, right? Can you show the tables struct? Thus, I can see this more easily.

**Comment by lazychaser** [comment]
```
id
nestedset
team_id
```

That's all. Each node is a match, meaning that it contains the winner. So, for two teams there will be 2 leaves that reference `team_a` and `team_b`. Parent `match1` of this two nodes is a match that initially doesn't reference a team. After match it will hold a reference to the winner. This expands to the whole tree. You can have two more teams `team_c` and `team_d`, that will play `match_2`. Now you have two nodes `match_1` and `match_2` that have parent `match_3`.

**Comment by regiszanandrea** [comment]
Thanks for the answer, I did understand you but I don't now where I have to save the two teams, on nestedset? If Yes, how I do that?

**Comment by lazychaser** [comment]
There is no `two teams`, each node is a team. Last nodes (leaves) are just initial teams, ancestors of those are matches.

```
Winner of match 3
   Winner of match 1
      Team A
      Team B
   Winner of match 2
      Team C
      Team D
```

**Comment by regiszanandrea** [comment]
Oh, now I see. Thanks for attention @lazychaser. I appreciate it.
