### ISSUE TITLE
Method getKey does not exist

### ISSUE THREAD

**Issue by ghost** [lazychaser/laravel-nestedset#257]
Приветсвую.
Обновился на Laravel, начиная с v5.5.29 появилась проблемка:
Method getKey does not exist
в файле vendor/kalnoy/nestedset/src/Collection.php
```
protected function flattenTree(self $groupedNodes, $parentId)
    {
        foreach ($groupedNodes->get($parentId, []) as $node) {
            $this->push($node);

            $this->flattenTree($groupedNodes, $node->getKey());
        }

        return $this;
    }
```
Может это только у меня, пока конкретно не разбирался, ну и пока не кретично т.к. dev

**Comment by lazychaser** [comment]
`getKey` -- это стандартный метод для `Model`

**Comment by ghost** [comment]
Хорошо. Спасибо!
Буду разбиратся в своем коде...

**Comment by ghost** [comment]
Ха! :D
Отбой тревоги...
Обновился на v5.5.32, все снова прекрасно работает, а то я уж растроился, пол года работало, а тут... снова... воспроизводить прошедшее время...
Чет их там плющит..., на ларе.
P.S.
Спасибо вам за ваш super пакет!!!
Всего вам хорошего!

**Comment by lazychaser** [comment]
Спасибо, и Вам =)
