### ISSUE TITLE
field name value not added

### ISSUE THREAD

**Issue by ZiarAdjel** [lazychaser/laravel-nestedset#260]
with db:seed i cannot insert values in field 'name' 
i use Doc Example
`$node = Category::create([
'name' => 'Foo',
'children' => [
[
'name' => 'Bar',

'children' => [
[ 'name' => 'Baz' ],
],
],
],
]);`

**Comment by lazychaser** [comment]
See `fillable` on laravel docs

**Comment by ZiarAdjel** [comment]
this my model

> class Category extends Model
{
    use NodeTrait, Translatable;

    protected $table = 'categories';
    public $timestamps = true;
    public $translatedAttributes = ['name'];
    protected $fillable = ['name'];
}
