### ISSUE TITLE
Question: Bulk remove

### ISSUE THREAD

**Issue by kossa** [lazychaser/laravel-nestedset#263]
Hello,

I want to remove several categories(without children) currently I'm using this code : 

```
DB::table('place_categories')->whereIn('id', $ids)->delete();
```

Current there is no problem, but it cause a tree break or no ?

Thank you

**Comment by lazychaser** [comment]
Yes it does

**Comment by kossa** [comment]
Thank you for the quick answer :)

**Comment by lazychaser** [comment]
https://github.com/lazychaser/laravel-nestedset#deleting-nodes

**Comment by kossa** [comment]
i have read this section before, I'm asking for a bulk delete not one by one ;)

**Comment by lazychaser** [comment]
> IMPORTANT! Nodes are required to be deleted as models

**Comment by kossa** [comment]
Great, please this way is it correct ?
```php
foreach ($ids as $id) { // $ids array of category id I want to delete
    $cat = Category::find($id); // This is a category model
    $cat->delete();
}
```

**Comment by lazychaser** [comment]
```php
foreach (Category::whereIn('id', $ids)->get() as $category) $category->delete();
```

**Comment by kossa** [comment]
Thank you for the answer much optimized :)
