### ISSUE TITLE
Update to Laravel 5.6

### ISSUE THREAD

**Issue by rjsworking** [lazychaser/laravel-nestedset#265]
Hi

Thanks for this awesome package. I'm upgrading a L5.5 project but your package doesn't install on L5.6 (yet :) ).

Thanks in advance

**Comment by lazychaser** [comment]
Laravel 5.6 is already released? Wow. Ok.

**Comment by rjsworking** [comment]
Hi. It will released in a few days after Laracon Online:
https://twitter.com/taylorotwell/status/958725579066499072

Cheers

**Comment by lazychaser** [comment]
Done.

**Comment by rjsworking** [comment]
Thank you very much :)

Cheers
