### ISSUE TITLE
fixTree does not work with Esensi Model

### ISSUE THREAD

**Issue by herryswastika** [lazychaser/laravel-nestedset#269]
Dear Mr Kalnoy, first of all, your package is really great, many thanks for this n God bless. 
I'd like to report that if I choose "use \Esensi\Model\Model;", the fixTree() does not work i.e. _lft and _rgt are still zero. But if I choose "use Illuminate\Database\Eloquent\Model;", all are working well. 
A side question: I've managed to use traverse function in the Blade view with the proper "a list-group-item href route" etc etc, however is there any way that the output will be 
1 Root
1.1 Child 1
1.1.1 Sub child 1
1.2 Child 2
2 Another root
instead of:
- Root
-- Child 1
--- Sub child 1
-- Child 2
- Another root
Many thanks
Rgds,
Herry

**Comment by lazychaser** [comment]
Hi. I do not guarantee correct work with other packages. And I also do not consult about the usage of the package.
