### ISSUE TITLE
How to get the whole tree

### ISSUE THREAD

**Issue by ghost** [lazychaser/laravel-nestedset#272]
Hi,
Thanks for a great package!
Is it possible to get the whole tree (all related nodes) from a node?

Kind regards,
Salvis

**Comment by ashgibson** [comment]
This seems to be missing, I would have thought you could do something simply like 

> MyNode::find(1)->toTree(); 

But instead you need to do this 

> MyNode::where('id', 1)->get()->toTree();

There is the ability to do 

> MyNode::find(1)->descendants

 and then do your own logic for shaping the data into a tree.

**Comment by lazychaser** [comment]
`$node->descendants->toTree()`

**Comment by ghost** [comment]
In this case, querying descendants work only if the $node is a root node.

What I meant was to get the whole tree from whatever node in the tree structure - get all of it's siblings, ancestors and descendants.

The following code works for me, but I thought maybe there is a shorter approach.

`if ($this->company->isRoot()) $wholeTree = Company::descendantsAndSelf($this->company->id);`
`else $wholeTree = Company::descendantsAndSelf($this->company->ancestors()->whereIsRoot()->first());`

**Comment by lazychaser** [comment]
This is not true, descendants are available from any node.

**Comment by ghost** [comment]
@lazychaser Yes, but it will return only descendants, but not what I'm asking for. :)

> What I meant was to get the whole tree from whatever node in the tree structure - get all of it's siblings, ancestors and descendants.

**Comment by lazychaser** [comment]
Ah, well, then, your aproach to take root ancestor's descendants is fine.
