### ISSUE TITLE
Conflict with jenssegers/laravel-mongodb

### ISSUE THREAD

**Issue by Rikcon** [lazychaser/laravel-nestedset#274]
Hello, after updating i found that laravel-nestedset and laravel-mongodb conflicting with following error:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait method newEloquentBuilder has not been applied, because there are collisions with other trait methods on App\Course
```

I think that's because in my model there's following code: 

`class Course extends Model
{
    use HybridRelations;
    use NodeTrait;`

So i use NodeTrait from laravel-nestedset, and HybridRelation from laravel-mongodb, both of those implement newEloquentBuilder method. 

Do you have any ideas how to fix this ? 
Because i need both of those packages 100%

Thank you for your time !

**Comment by mohammad-fouladgar** [comment]
Hi,
Currently, this package not support the MongoDB.

**Comment by lazychaser** [comment]
Hi. You'll need to make an adapter on your own.
