### ISSUE TITLE
How do I get ancestors as JSON data

### ISSUE THREAD

**Issue by mdasiff** [lazychaser/laravel-nestedset#275]
I want to get ancestors in json data this is my code:
public function show(Category $category)
    {
        $ancestors = Category::ancestorsOf($category);
        return response()->json(['category'=>$category, 'ancestors'=>$ancestors]);
    }
//I dont know in ajax how can call the ancestors.

**Comment by lazychaser** [comment]
Oh, guys, do I look like PHP/Laravel tech support?
`response()->json([ 'category' => $category->toArray(), 'ancestors' => $ancestors->toArray() ]);`

**Comment by mdasiff** [comment]
Sorry if I hurts you. By the way I love helping others in programming.
