### ISSUE TITLE
get tree from some leaves

### ISSUE THREAD

**Issue by Mont4** [lazychaser/laravel-nestedset#279]
I choose some leaves and i want just get ancestors of this nodes. i want make a tree from this leaves and their ancestors.

```php

                $categories = Product::CompanyId($id)
			->select('category_id')
			->groupBy('category_id')
			->get();

		// TODO. Category with parent
		$nodes = Category::whereIn('id', $categories)
			->leaves()
                          ->ancestors()
			->toTree();

```

**Comment by lazychaser** [comment]
You need to load ancestors eagerly and merge everything to a single collection and call toTree on that.

**Comment by mohammedabdallah** [comment]
@lazychaser  If we have a tree-like this one
![Clothing-hierarchy-traversal-2 svg](https://user-images.githubusercontent.com/15056634/98466513-bea3f200-21d8-11eb-8e00-e31c566b5712.png)
can I build a tree If I have the IDs of (slacks, jackets, sun Dresses ) ?
in general, I have the last level nodes ids and I need to build the tree from the bottom nodes I have
