### ISSUE TITLE
Model's keyName shouldn't need to be fillable

### ISSUE THREAD

**Issue by isecchin** [lazychaser/laravel-nestedset#283]
First of all, great package, @lazychaser !

I've started to use it a few days ago and it's been working wonderfully !

Just something I stumbled today, when trying to rebuild the tree from an array using the `rebuildTree()` function, I had to do a little tweak for it to work as I was expecting.
I don't like much the idea of having the model's key as a fillable property, and I think this is a standard on the Laravel community (at least it felt like it for me).
But the way the `buildRebuildDictionary()` function is implemented, it sends the full array of data as an argument to the Eloquent's `fill()` method (excluding only the 'children' attribute, which is used for recursivity later on).
This causes a MassAssignment exception if the model's keyName is not set as fillable, but since the function already checks whether the model exists or not and the key is already set for the model, a simple solution for this problem is to just unset the keyName in the `$itemData` array:

```php
if (! isset($itemData[$keyName])) {
    // ...
} else {
    // ...
    unset($itemData[$keyName]);
    unset($existing[$key]);
}
```

At least for me it seemed like this solution works, but I'm not sure if it's intended to work as it is now or if this should be fixed.
I think I can create a pull request with this solution if it's accepted.

Cheers !

**Comment by lazychaser** [comment]
Hello. As far as I remember, MassAsignmentException is thrown when fillable is not set and guarded is set to *.

**Comment by isecchin** [comment]
Ok, I found what my problem was !
You're right about the MassAssignmentException, I was a bit too quick here and didn't debug very well the issue before hahaha
The problem was that the way I was building my models, I was injecting some configuration properties that set the fillable attribute, but when using the `$model->newInstance()` method, the fillable attribute was not being populated and was leading to the exception.
I'll close this issue, since it was a problem on my part, I'm sorry for the misunderstanding !
