### ISSUE TITLE
create static fails

### ISSUE THREAD

**Issue by sandrodz** [lazychaser/laravel-nestedset#29]
I'm having trouble understanding how to save a root node.

I've tried:
{{{Category::create([
		'title' => 'Logos',
		'slug' => 'logos',
		'description' => 'blah bluh ipsum ma',
		'_lft' => 0,
		'_rgt' => 0
	]);}}}

But I've a feeling I shouldn't specify _lft _rgt manually and that should managed by the script itself on first create.

Am I wrong in assumptions?

**Comment by lazychaser** [comment]
Sure, no need to specify _lft and _rgt when you create a node, no matter
where do you want to put it.

2015-01-11 14:01 GMT+03:00 Sandro Dzneladze <notifications@github.com>:

> I'm having trouble understanding how to save a root node.
>
> I've tried:
> {{{Category::create([
> 'title' => 'Logos',
> 'slug' => 'logos',
> 'description' => 'blah bluh ipsum ma',
> '_lft' => 0,
> '_rgt' => 0
> ]);}}}
>
> But I've a feeling I shouldn't specify _lft _rgt manually and that should
> managed by the script itself on first create.
>
> Am I wrong in assumptions?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/lazychaser/laravel-nestedset/issues/29>.
>



-- 
Best regards, Alexander Kalnoy.
