### ISSUE TITLE
scope error:: Column not found: 1054 Unknown column 'products._lft' in 'where clause'

### ISSUE THREAD

**Issue by mdasiff** [lazychaser/laravel-nestedset#290]
I'm getting error while fetching products based on nested set.
**"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'products._lft' in 'where clause' (SQL: select *, (select count(1) - 1 from `products` as `_d` where `_d`** 
Fetching product like this
`$products = Product::scoped(['category_id'=>1])->withDepth()->get();`

**Comment by angelhappyboy** [comment]
Do you use the nested set befor?
You should make sure your table have "_lft" column.

**Comment by mdasiff** [comment]
Yes I'm using nested set for category please have look on **category table**
![category_table](https://user-images.githubusercontent.com/35130721/39186244-628afde2-47e7-11e8-89cb-f8d8818bd113.JPG)

By the product table does not contain "_lft" column, Please have a look on **product table**
![product_table](https://user-images.githubusercontent.com/35130721/39186275-8c60810a-47e7-11e8-8020-ba1318e10711.JPG)

**Comment by mdasiff** [comment]
Sir please answer my question, This error still punishing me.
I have One to Many relationship between Category and Product model.
Product.php
`use Kalnoy\Nestedset\NodeTrait;
class Product extends Model
{
  use NodeTrait;
  protected function getScopeAttributes()
  {
    return ['category_id'];
  }
  public function category()
  {
    return $this->belongsTo(Category::class);
  }
}`

**Comment by lazychaser** [comment]
If Product is not a Node, why would you expect it to be a Node?

**Comment by mdasiff** [comment]
I corrected my code its working well. But I have a big milestone, If you help me it would be appreciated. 
When the user selects a certain category, the system able to show products that belong to that category. But now, the need has come to show products that belong to categories under the selected category. I can pay you a little bit of amount if you don't mind. Your nested libraries is very helpful for me for create nested set of category. Its an humble request. Thanx.

_Here is an example to clarify things:_
**Categories**

Fashion Store -> Girls Clothing -> Maternity Wear -> Show related products
Fashion Store -> Girls Clothing -> Show related Products
Fashion Store ->Show related Products also related to its nested set categories
------------------------------
_My Code_
**Category Model**
use Kalnoy\Nestedset\NodeTrait;
class Category extends Model
{
    use NodeTrait;
    

    public function products()
    {
        return $this->hasMany(Product::class);
    }
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }
    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }
    
    public function ancestors()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function descendants()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }
    protected function getScopeAttributes()
    {
        return ['parent_id'];
    }
}
**Product Model**
public function category()
    {
    	return $this->belongsTo(Category::class);
    }
**Product Model**
public function category()
    {
    	return $this->belongsTo(Category::class);
    }
**Product Controller**
public function eachRoute($slugs = null)
    {
        if($slugs) 
        {
            $slugs = explode('/', $r);
        }
        $products = Product::findByCategorySlug($slugs)->get();
        return view('testp',['products'=>$products]);
    }

**Comment by lazychaser** [comment]
There is an example in the docs of how to get all items in the specified node and all of it's descendants.
