### ISSUE TITLE
Add "_depth" and "_children_count" columns to db

### ISSUE THREAD

**Issue by ghost** [lazychaser/laravel-nestedset#291]
Can we store "_depth" and "_children_count" in db and update it while re-syncing _lft and _rgt.
_depth: Root Node = 0 and So on.
_children_count = Recursive count of all children of a node.

**Comment by lazychaser** [comment]
Yes we can

**Comment by ghost** [comment]
Can you add this into feature request.

**Comment by lazychaser** [comment]
No, sorry, this is relatively rarely used feature that raises the complexity event further.

**Comment by ghost** [comment]
But while building the tree you already have depth and children. So, basically it requires to store the depth and count(children) in db.

Also, while calculating lft and rgt, can you use "position" or other some other column to sort children. As of now it uses primary column only.

**Comment by lazychaser** [comment]
I can't quickly measure depth when updating a tree.

Sorting: https://github.com/lazychaser/laravel-nestedset#default-order
