### ISSUE TITLE
Tree by Nodes

### ISSUE THREAD

**Issue by minuwan** [lazychaser/laravel-nestedset#292]
Getting the entire tree by nodes using `Model::defaultOrder()->get()->linkNodes();` is awesome, Wonder is there any way we can get specified node's childrens (In one query or less) ?

Maybe something like  `Model::whereIn('id', [1, 2, 3])->defaultOrder()->get()->linkNodes();` ?

Any method or a workaround to solve this? Also, wonder the way to `pluck` columns recursively.

Purpose: Build URLs from given posts (slugs). @lazychaser

**Comment by lazychaser** [comment]
`Model::whereIn('id', [1, 2, 3])->with('children')`?

**Comment by minuwan** [comment]
@lazychaser I tried that, `whereIn` ignores the `->with('children')` part somehow.

It only query the given id. For instence, `Model::whereIn('id', [4])->with('children')->get()` is same as `Model::whereIn('id', [4])->get();` when I tried. returned childrens as `"children": []`

**Comment by minuwan** [comment]
@lazychaser 

`Model::with('children')->get()->linkNodes();` ================>Works Fine

`Model::whereIn('id', [4])->with('children')->get()->linkNodes();` ==> Broken

**Comment by minuwan** [comment]
@lazychaser My ultimate goal is to generate the following result, When I provided page01's id and page03's id `whereIn('id', [1, 3])`: 

[
{"page01"},
{"page01",  "page02", "page03"}
]

So I can later generate it as:

https://example.com/page01
https://example.com/page01/page02/page03

Note: **page03**'s parent is **page02**, **page02**'s parent is **page01**

**Comment by lazychaser** [comment]
`Model::whereIn('id', [1, 2, 3])->orWhereIn('parent_id', [1,2,3])->get()->linkNodes()`

**Comment by minuwan** [comment]
Yes, We are getting closer @lazychaser, But the problem is to get children's of 01 and 03 including itself, only using those two ids (01, 03) and do it in an efficient manner (One query or less).

Another way to approach this problem... `Model::ancestorsAndSelf(3)->linkNodes()[0];` Isn't it great if we can provide multiple ids... Kind a like: `Model::ancestorsAndSelf([1, 3])->linkNodes();`

So the result will be like...

[
{"page01"},
{"page01", "page02", "page03"}
]

Note: I used `[0]` to get the first result which is the correct one in the first case.
