### ISSUE TITLE
Get only left descendants from a node?

### ISSUE THREAD

**Issue by forddyce** [lazychaser/laravel-nestedset#294]
Say i have:

```
          A
       /       \
     B        C
  /      \
D       E
```

Can i get only **B, D, E** using something similar like `$node->descendants;` ?

**Comment by lazychaser** [comment]
NestedSets are not binary trees, so there is not such term like left sibling or right.  You can state that node with least _lft value is left, so: `Category::query()->where('parent_id', 'A')->with('descendants')->orderBy('_lft')->first()`

**Comment by jason-guru** [comment]
I have created a binary tree using NestedSets. Here's how it works, 

Assign a side/order id to every child that is assigned to a node, and store it in the database while creating the child.
Now, as per your example A is the node and B & C are it's children. So, B will have side/order id 1 and C will have side/order id 2.

First of all Get A, like $user = User::findOrFail(A); 

Then it's children like,
$B = $user->children->where('side_id', 1)->pluck('id')->toArray(); 
$C = $user->children->where('side_id', 2)->pluck('id')->toArray();

$BAsChild = User::findOrFail($B[0]);
$CAsChild = User::findOrFail($C[0]);
Now get B's descendants and self, by $BAsChild->descendantsAndSelf($BAsChild->id); 

You will get B,D and E.
