### ISSUE TITLE
How to work with API Resources?

### ISSUE THREAD

**Issue by Insua** [lazychaser/laravel-nestedset#296]
If I use API Resources to transform the tree data by TreeResource::collection(TreeData)->toTree(),it does not work,coz after trasnform by API Resource ,it's a resource and it have not toTree methods, but I want to use API Resources,any ideas for me?

**Comment by ferryvg** [comment]
Use:
`TreeResource::collection( TreeData->toTree() )`

Resource class example
`class TreeResource extends JsonResource`
`{`
`    public function toArray($request)`
`    {`
`        $resource = parent::toArray($request);`
`        $resource['children'] = TreeResource::collection($this->children);`
`        retrun $resource;`
`    }`
`}`

**Comment by Insua** [comment]
@ferryvg thinks for sovle my problem
