### ISSUE TITLE
Move node to another parent

### ISSUE THREAD

**Issue by leonguyen** [lazychaser/laravel-nestedset#30]
Hi, I have problem with moving node to another parent, here is my function:
```
public function update($id, $data) {
	$row = $this->model->find($id);

	$parent = $this->model->find($data['parent_id']);
	if ($row->appendTo($parent)->save()) {
		$moved = $row->hasMoved();
		//return $moved;
	}
	$row->fill($data);
	return $row->save();
}
```
And the $moved return false.
Sorry to my English not good.

Thanks.

**Comment by lazychaser** [comment]
First of all, changing `parent_id` property on model automatically changes it and no need to save the model twice:

```php
public function update($id, $data) {
    $row = $this->model->find($id);

    return $row->fill($data)->save();
}
```

Regarding your problem, you should check whether the parent is actually different. If it is, check whether the node is moved in database, if it is, maybe something wrong with with `hasMoved` check.

**Comment by Antonimo** [comment]
works only on new models. on existing model dirty is empty.
