### ISSUE TITLE
Is there any simple way to get relations all child nodes while querying parent node?

### ISSUE THREAD

**Issue by monurakkaya** [lazychaser/laravel-nestedset#301]
First of all, I personally thank you for this great package!

I don't know if title is clear enough or not. Let me give an example: 

- User1
  - User2
  - User3 
    - User 4

Let's say we have a structure like above. And each user has many transactions. What i need help to improve my queries: 

How can get User1,2,3,4 transactions when User1 is selected? 

How can get User3,4 transactions when User3 is selected? 

Is there anyway to do this quick and easily? 

If User2 selected i can easily do `$user2->transactions` but when the admin clicks on user1 here is the mess: 

```
$descendants = $user1->descendants()->whereHas('transactions', $filter = function ($query) {
            $query->valid()->latest();
        })->with(['transactions' => $filter])->get();

$transactions = $user1->transactions()->valid()->latest()->get();
foreach ($descendants as $descendant) {
    $transactions = $transactions->merge($descendant->transactions);
}

return $transactions // parent and node transactions
```

Any help would be appreciated.

**Comment by lazychaser** [comment]
https://github.com/lazychaser/laravel-nestedset#getting-related-models-from-other-table
