### ISSUE TITLE
Genealogy application using nestedset - query

### ISSUE THREAD

**Issue by curtisdelicata** [lazychaser/laravel-nestedset#303]
Can this be used for a tree which requires two parent_id? Sometimes if one parent is unknown it might not require two parent id so would be null for one also.

It is for a genealogy application.

I'm trying to decide if I should modify this module or just keep using pivot tables?

**Comment by lazychaser** [comment]
This package cannot be used for building genealogy tree, because it is actually a graph. You can still use it for building simple trees where in the root will be YOU with two children that are your father and mother, and so on.

**Comment by curtisdelicata** [comment]
Thank you for clarifying.
