### ISSUE TITLE
Paginate not working with method  "whereDescendantOf"

### ISSUE THREAD

**Issue by zeroiszero** [lazychaser/laravel-nestedset#308]
`Node::whereDescendantOf($node)->paginate($this->article_category_per_page);`

pagination like this will not return correct results.

`Node::whereDescendantOf($node)->get();`  this will get correct results

**Comment by lazychaser** [comment]
Sure it won't return correct results. Try `Node::whereDescendantOf($node)->limit(10)->get();` -- it will also won't return correct results, because tree cannot be built out of portion of nodes.
