### ISSUE TITLE
Ordering the Descendant list

### ISSUE THREAD

**Issue by noelwalsh** [lazychaser/laravel-nestedset#31]
Thanks for the package, it looks perfect for building a tree view in my app. 

That said, when I reorder the nodes, using down() and up(), I can see they left and right values adjusting, but I can't find any way to read them back in the new order. Instead, they're always returned in the same order, which I guess is the original insertion order, even if I call the toTree method.

Is there any method provided to do this sorting or is up to me to do it manually?

N

**Comment by lazychaser** [comment]
Hi!

Use defaultOrder method on query builder to order by lft value.
22 ñÎ× 2015 Ç. 0:10 ÐÏÌØÚÏ×ÁÔÅÌØ "noelwalsh" <notifications@github.com>
ÎÁÐÉÓÁÌ:

**Comment by noelwalsh** [comment]
Thanks for the reply, but I can’t see how to get this to work 

As I’ve multiple trees in the table, I’ve tried reading the data for just one using a query like

	$list = Table::defaultOrder()->where(‘x’, ‘=‘, 1000->get(1) ;

which does return the nodes in the _lft order. However, when I attempt to transform this to a tree using

	$list->getDescendants()->toTree()->toArray()  ;
or
	$list->toTree()->toArray() ;

it fails with undefined methods of getDescendants or toTree.

Am I doing something wrong? Basically, how do I retrieve the complete tree in the actual stored tree order?

And really, since the package is dedicated to supporting nesting, I think it would be sensible to have this action as the default behaviour, without the requirement to apply additional ordering criteria.

Noel Walsh
Crewe IT
Tel: 07951 183 553

**Comment by lazychaser** [comment]
Get descendants is only available for a single node. As for the ordering,
someone would want to order by some other criteria.
22 Янв 2015 г. 16:21 пользователь "noelwalsh" <notifications@github.com>
написал:

**Comment by noelwalsh** [comment]
I’m sure they would, but I do think the obvious default should be the sorted order.

But you didn’t tell me how to access the complete tree in the sorted order. Is it possible please?

Noel Walsh
Crewe IT
Tel: 07951 183 553

**Comment by lazychaser** [comment]
>I’m sure they would, but I do think the obvious default should be the sorted order.

This behaviour used to be in previous version and caused many problems, so I decided to make it optional.

> But you didn’t tell me how to access the complete tree in the sorted order. Is it possible please?

```php
Table::defaultOrder()->get()->toTree();
```

**Comment by noelwalsh** [comment]
Thanks you Alexander, after adding a where clause to limit to the particular tree I required, that did the trick


Noel Walsh

**Comment by lazychaser** [comment]
I've pushed a new commit where `getDescendands` applies default order by default, so you can do following:

```php
$node = Table::where('x', '=', '1000)->find();

$descendands = $node->getDescendands()->toTree();
```

**Comment by noelwalsh** [comment]
That’s brilliant Alexander.

Thanks very much for your help

Noel Walsh
