### ISSUE TITLE
Conflict with Laravel/Scout on softDelete

### ISSUE THREAD

**Issue by zhiyong-ft** [lazychaser/laravel-nestedset#310]
When I tried to add both NodeTrait and [Searchable](https://github.com/laravel/scout) to a model, I get the following error:
```
Trait method usesSoftDelete has not been applied, because there are collisions with other trait methods on App\Models\MyModel
```
Laravel 5.5.43, Laravel/Scout 4.0

NestedSet: 4.3.3

**Comment by zhiyong80** [comment]
I am able to proceed after renaming usesSoftDeletes to something else. Shall I fork then PR?

**Comment by zhiyong-ft** [comment]
I was able to resolve the matter with conflict resolution. Please close the issue.

**Comment by jaspergeertsma** [comment]
So what was the solution?

**Comment by it4need** [comment]
For all other people: 

The solution is to use conflict resolution of the trait method.

```
use Searchable {
        \ScoutElastic\Searchable::usesSoftDelete insteadof \Kalnoy\Nestedset\NodeTrait;
}
```

**Comment by AurelienMendes** [comment]
Thanks @it4need for your solution, but I don't understand how, with it, you can have Nestedset working (since now the Nestedset usesSoftDelete method is no more used ) ?

**Comment by adgower** [comment]
Thanks! still working:
```
use NodeTrait;
use Searchable {
    \Laravel\Scout\Searchable::usesSoftDelete insteadof \Kalnoy\Nestedset\NodeTrait;
}
```
