### ISSUE TITLE
Where condition

### ISSUE THREAD

**Issue by eoikoncept** [lazychaser/laravel-nestedset#313]
Can I add a where condition when inserting a node and can I also add a where condition when fixing a tree. If yes, please where can I do that

**Comment by lazychaser** [comment]
See scoping feature

**Comment by eoikoncept** [comment]
Thanks, just what I needed, but please why does parent_id convert to null when I fixtree

**Comment by lazychaser** [comment]
Make sure you're using it like so `Category::scoped([ 'scope_attr' => $value ])->fixTree();`

**Comment by eoikoncept** [comment]
Thanks

**Comment by eoikoncept** [comment]
This is my example 
Referral::scoped(['level' => 5])->fixTree() and it updated all the parent_id fields to null, what do you think might be wrong. Thanks for your assistance

**Comment by lazychaser** [comment]
You cannot fix nodes on a certain level. You can only fix a subtree or whole tree
