### ISSUE TITLE
Deleting a menuitem row from Nestedset table containing menuitems from different menu 

### ISSUE THREAD

**Issue by yelnyafacee** [lazychaser/laravel-nestedset#316]
hi, I have a nestedset table `menuitems`, containing items from different menus, and identified with the `menu_id` `foreign_key` column.

I have 3x existing menus ( `menu_id` = 1, 2, 3 ), and I want to delete a menuitem from menu 3 form the above table

like:
```
    public function deleteByModel( Model $menuitem )
    {

        DB::transaction(function () use ($menuitem) {

            // Delete > SUCCESS
            if ($menuitem->delete()) {

                return true;
            }

            // Delete > FAILED
            throw new SomeException(trans('exceptions.some_error'));
        });

    }
```

is this correct? or do I need to add in more conditions like: `$menu->where('menu_id', 3)` etc?

will the function above mess up the `_lft` and `_rgt` values of `menu1` and `menu2` items in the same table?

**Comment by lazychaser** [comment]
If you set up scoped attributes properly, everything should be fine.
