### ISSUE TITLE
How to keep an order updating category

### ISSUE THREAD

**Issue by Anatoliy-Petrov** [lazychaser/laravel-nestedset#320]
Now if update root category, it goes down to the bottom of the tree (according to defaultOrder), like a created one. How can I keep the order in a tree if I'm just updating some category?

**Comment by lazychaser** [comment]
It shouldnt if you are selecting node with `defaultOrder`

**Comment by Anatoliy-Petrov** [comment]
the problem is it's overwriting _lft and _rgt while updating, I don't know yet how to fix it

**Comment by Anatoliy-Petrov** [comment]
got it. tricky thing, if I'm updating root category and overwhriting parent_id even from null to null, not touching _lft and _rgt - it's overwriting indexes, but if I don't touch parent_id at all - it goes well
