### ISSUE TITLE
Hi there I couldn't find how to get only parent nodes(categories) 

### ISSUE THREAD

**Issue by zheldibayev** [lazychaser/laravel-nestedset#321]
$categories = Category::whereNull('parent_id')->get(); 
I get all parent nodes like this. Is it correct or I can do it another way?

**Comment by lazychaser** [comment]
You mean all root nodes?

**Comment by zheldibayev** [comment]
> You mean all root nodes?

Yes

**Comment by lazychaser** [comment]
`Category::whereIsRoot()->get()` But your method is what `whereIsRoot` does

**Comment by zheldibayev** [comment]
> `Category::whereIsRoot()->get()` But your method is what `whereIsRoot` does

Thank you for your quick reply. It works. I just wanted to make my code more clear. Thanks a lot
