### ISSUE TITLE
Query builder missing "whereDescendantAndSelf" method

### ISSUE THREAD

**Issue by anlamas** [lazychaser/laravel-nestedset#324]
Hello, thanks for this awesome package.
In documention u mentioned about that method, but its missing.
I know i can pass arguments and get what i need, but its a very helpfull alias method.
UPD: same thing with whereAncestorAndSelf

**Comment by lazychaser** [comment]
Seems like you are using old version

**Comment by anlamas** [comment]
`composer show`
`kalnoy/nestedset                      v4.3.3     Nested Set Model for Laravel 4-5`
Searching QueryBuilder class for "whereAncestorAndSelf/whereDescendantAndSelf" and nothing

**Comment by anlamas** [comment]
searching "whereAncestorAndSelf/whereDescendantAndSelf" in this 
[https://github.com/lazychaser/laravel-nestedset/blob/v4/src/QueryBuilder.php](url)
and nothing

**Comment by lazychaser** [comment]
`whereDescendantOrSelf`
`descendantsAndSelf`

**Comment by anlamas** [comment]
Why u close issue?
1. In documentation u mentioned about query builder method. 
`Category::whereDescendantAndSelf($id)->get();`
2. `descendantsAndSelf` its not readable.
`Category::query()->descendantsAndSelf($id);`  its unclear what method does and reading like local scopes
`Category::query()->whereDescendantAndSelf($id)->get();` everything is clear here

I mean, u left `OrSelf` methods.
There is no chance return back whereAncestorAndSelf/whereDescendantAndSelf?

**Comment by lazychaser** [comment]
Please read documentation carefuly: 
`$result = Category::whereDescendantOrSelf($node)->get();`
`$root = Category::descendantsAndSelf($rootId)->toTree()->first();`

**Comment by anlamas** [comment]
[https://github.com/lazychaser/laravel-nestedset#constraints](url)
Descendants constraints:

$result = Category::whereDescendantOf($node)->get();
$result = Category::whereNotDescendantOf($node)->get();
$result = Category::orWhereDescendantOf($node)->get();
$result = Category::orWhereNotDescendantOf($node)->get();
**$result = Category::whereDescendantAndSelf($id)->get();**

I dont know, i think its coz of my bad english, i cant tell u point my view.

You keep writing me about `whereDescendantOrSelf`, man i know it about that. I never asked u.
Yes, i know about `descendantsAndSelf` too. But its just unclear method when **u read code**.

I asked u about `whereDescendant**And**Self` method, just like existing `whereDescendant**Or**Self`.
Why can exists `whereDescendant**Or**Self` method and cant  `whereDescendant**And**Self`.

**Comment by lazychaser** [comment]
Because its the same. `whereDescendantsAndSelf` cannot exists, because this means that we want to select descendants **and** self, which means only self. You can read this as `whereDescendants()->andWhereSelf()`, whereas it should be `whereDescendants()->orWhereSelf()`.
