### ISSUE TITLE
So may queries on User::fixtree();

### ISSUE THREAD

**Issue by ahsanmster** [lazychaser/laravel-nestedset#331]
I've used this library to maintain my users, I've approx 18k users right now in my test db and i have to run user:fixtree() on each register, when i check the logs the user::fixtree() cause 18k queries to run which slows down my server and my register process as well. because its running on complete users table.

I want to modify it as that it should fix only the user i created or may be run limited number of queries to make my process smooth.

**Comment by lazychaser** [comment]
Don't use fix tree on each register. It updates each model

**Comment by ahsanmster** [comment]
> Don't use fix tree on each register. It updates each model

what do you suggest i should do?

**Comment by lazychaser** [comment]
Please read documentation and use methods for inserting nodes.
