### ISSUE TITLE
Defining parent using manual attribute assignment not working

### ISSUE THREAD

**Issue by antonkomarev** [lazychaser/laravel-nestedset#336]
If you will redefine `parent_id` with `getParentIdName()` method then attribute assignment will be ignored.

```php
class Category
{
    public function getParentIdName()
    {
        return 'parent_category_id';
    }
}
```

This wouldn't work:
```php
$shop->categories()->create([
    'parent_category_id' => $parentCategory->getKey(),
    'title' => 'Title',
]);
```

But this will work:
```php
$shop->categories()->create([
    'parent_id' => $parentCategory->getKey(),
    'title' => 'Title',
]);
```

I've tested another one approach, and it's working:
```php
$category = $shop->categories()->create([
    'title' => 'Title',
]);

$category->appendToNode($parentCategory)->save();
```

But as you can see it's +1 query. And there is no easy way to create factory in tests:

I have to do:
```php
$subcategories = factory(Category::class, 2)->make();
$subcategories->get(0)->appendToNode($category)->save();
$subcategories->get(1)->appendToNode($category)->save();
```

Instead of:
```php
$subcategories = factory(Category::class, 2)->create([
    'parent_category_id' => $category->getKey(),
]);
```

**Comment by antonkomarev** [comment]
That's happen because this logic is hidden in `setParentIdAttribute` magic method of the `NodeTrait` which wouldn't be called if column name is custom.

Test case is added in PR #337

**Comment by antonkomarev** [comment]
I've found that I've missed this part of documentation:

```php
// Specify parent id attribute mutator
public function setParentAttribute($value)
{
    $this->setParentIdAttribute($value);
}
```

So in my case I were needed to add:
```php
public function setParentCategoryIdAttribute($value)
{
    $this->setParentIdAttribute($value);
}
```

But maybe there is other way to solve this task, without requirement to add custom mutator?

Because from my point of view, search for parent shouldn't be done on attribute change. It should be done on `save` event.

**Comment by lazychaser** [comment]
This is just for convinience. You should use `appendToNode`
