### ISSUE TITLE
Scoping and eager loading is not working in version 4.3.3

### ISSUE THREAD

**Issue by janisdauksts** [lazychaser/laravel-nestedset#339]
Scoping and eager loading is not working in version 4.3.3
Result is empty when I try to get descendants with `Model::scoped(['category_id' => 1])->with(['descendants'])->find(1)`
In version 4.3.0 everything was ok.

**Comment by lazychaser** [comment]
Hi, descendants loading is tested. Please provide a test case when it fails.
