### ISSUE TITLE
Multiple nested set trees in the same database table

### ISSUE THREAD

**Issue by philipbrown** [lazychaser/laravel-nestedset#34]
Hi @lazychaser, this looks like an awesome package, nice work :smile:

How would you go about having multiple nested set trees in the same database table?

Would simply having multiple roots work? So modifying one tree won't affect any of the other trees.

[etrepat/baum](https://github.com/etrepat/baum) has the concept of [Scope](https://github.com/etrepat/baum#scope-support). I was just wondering if this is possible with your package?

Thank you :smile:

**Comment by lazychaser** [comment]
Hi! Thanks!

Sure you can use multiple trees, though updating one tree will affect actual values of `_lft` and `_rgt` of another tree, but proper order will remain and no sensible data will be lost.

Also, I think, [global scopes](http://laravel.com/docs/5.0/eloquent#global-scopes) might help here. It depends on your intent.

If you need to support multiple sites on same database, global query scope can help (you just apply condition like `where('site_id', '=', config('app.id'))`), if you need to store something like multiple menus, just assume that root node is a separate menu.

**Comment by philipbrown** [comment]
Ah cool, thank you. Yeah I need to use nested sets as part of a multi-tenant application.

I didn't think about using Global Scopes, I thought I might of had to implement the same functionality that is used in Baum, but I guess that was probably written before Global Scopes existed in Eloquent.

**Comment by lazychaser** [comment]
Yeah, I was requested for such feature long time ago before global scopes, and I though that this would overcomplicate the package. L4.2 introduced global scopes that can solve this problem perfectly.
