### ISSUE TITLE
Unable to use presenter on child nodes

### ISSUE THREAD

**Issue by pogachar** [lazychaser/laravel-nestedset#35]
Hi

I'm getting all pages with
```
$pages = $page->children()->get()->linkNodes();
```
and the presenter works fine on root nodes, but it doesn't work on children when I loop through them
```
@if($page->children()->count())
    @foreach($page->children()->get() as $page)
        {{ $page->urlTo }}
    @endforeach
@endif
```
I'm rewriting a site from L4 to L5 and would be nice to be able to reuse as much code as possible...
I originally used a different package (baum/baum), but it's not in development anymore

**Comment by lazychaser** [comment]
Hi. Thats because youre loading children each time in a loop by invoking
relation method children() rather than using filled value. Change
children()->get() to children
14 æÅ× 2015 Ç. 19:20 ÐÏÌØÚÏ×ÁÔÅÌØ "Jernej" <notifications@github.com>
ÎÁÐÉÓÁÌ:

**Comment by pogachar** [comment]
Thanks for a quick reply.

This only returns an empty collection on page with children.

**Comment by lazychaser** [comment]
```php
$pages = $page->getDescendands()->linkNodes();
```

```blade
@unless($page->children->isEmpty())
  @foreach ($page->children as $child)
  @endforeach
@endunless
```

**Comment by pogachar** [comment]
Sorry but I just can't get this to work properly...
```
public function index(Page $page) //all pages
{
	$pages = $page->getDescendants()->linkNodes();
	return view('admin.pages.index', compact('pages'));
}
```
throws ErrorException in QueryBuilder.php line 150: Undefined offset: 0

I also get this warning from time to time
```
Maximum function nesting level of '100' reached, aborting!
```

**Comment by lazychaser** [comment]
Sorry, man, I can't do it for you! There is a huge whitespace in understanding both how laravel and nestedsets work, please refer to the docs.

But, anyway, error in query builder just indicates that `$page` doesn't exists.
