### ISSUE TITLE
Trait collision when using with Plank Mediable

### ISSUE THREAD

**Issue by rzksbr** [lazychaser/laravel-nestedset#360]
I am using Plank Mediable for images and this throws an error 

> Trait method newCollection has not been applied, because there are collisions with other trait methods on App\Model\Category. 

Is there any way to avoid the trait collision?

**Comment by ChenRuihua** [comment]
same problem

**Comment by strykstaguy** [comment]
You can specify the specific trait you want to use the method from like this.

`use NodeTrait, Mediable {
        Mediable::newCollection insteadof NodeTrait;
    }`

**Comment by mefenlon** [comment]
I am having a similar issue. Has there been any solution proposed for this?
I am getting to collision using Cachable, Searchable  and NodeTrait on newEloquentBuilder and usesSoftDelete 
Would using insteadof reduce functionality of NodeTrait?
```
use Cachable, NodeTrait, Searchable {
        Searchable::usesSoftDelete insteadof NodeTrait;
        Cachable::newEloquentBuilder insteadof NodeTrait;
    }
```

**Comment by seek-x2y** [comment]
@mefenlon  
`Call to undefined method GeneaLabs\LaravelModelCaching\CachedBuilder::makeGap()`

 “You'll need to make an adapter on your own.” [#274](https://github.com/lazychaser/laravel-nestedset/issues/274)
