### ISSUE TITLE
Find by full path

### ISSUE THREAD

**Issue by ManiacTwister** [lazychaser/laravel-nestedset#37]
Hello,

I have a variable containing the full "path" (string with name and name of all parents seperated by |) of a category. For example ```"store|notebooks|apple"```. Now I would like to get the right category mathing this string. Sure, i could do ```Category::byName("apple")``` but if apple also exists in the ```mobile``` category this won't work.. Is there a nice way to do this?

**Comment by lazychaser** [comment]
I would recommend storing in database `full_path / category_id` association to find matching category. Or if you need this for url's you can just insert id into the url.

**Comment by ManiacTwister** [comment]
OKay, thanks for your answer. I'll try that out.

**Comment by str** [comment]
I don't understand the answer, "storing in the database full path", what if we move nodes around? Will the full path point to a wrong path? Do we need to also rewrite the move methods?

I'm also trying to find a way to do something similar to  `$node = Folder::fromPath('parentNode/subNode/finalNode');` to point to 'finalNode'

Is there something similar?
