### ISSUE TITLE
[Question] Duplicate/Clone Functionality

### ISSUE THREAD

**Issue by lazosweb** [lazychaser/laravel-nestedset#376]
I have a parent with children that I would like to duplicate it as a new parent because they have the same structure just different names. Is that even possible? Otherwise I have to recreate it manually...

**Comment by mmteyrek** [comment]
Hello,
Maybe this will help, I used this method to duplicate a menu :

    public function clone_menu(Request $request){
        $this->validate($request, [ 'code' => 'required'  ]);
        try{    
            if ( $this->group->group_origine == 1 && $this->group->group_level >300 ) {
                $menu = new Menu;
                $menu ->code = $request->input('code');
                $menu ->desc = $request->input('desc');
                $menu ->owner = 'C';
                $menu->save();

                $menu_new_id=$menu->id;

                $origine_id = $request->input('id');
                $nodes=MenuItem::scoped([ 'menu_id' => $origine_id ])->withDepth()->get();

                $nodes->map(function ($node) use ($menu_new_id) {
                    $node->menu_id= $menu_new_id;
                    return $node;
                });

                $nodes=$nodes->toTree();

                foreach($nodes as $node){
                    //$node->toJson();
                    $myArray = json_decode(json_encode($node), true);
                    $node_save = MenuItem::create($myArray);
                 }
                $nodes=MenuItem::scoped([ 'menu_id' => $menu->id ])->withDepth()->get()->toTree();
                $menu->nodes=$nodes;

                return $menu;
            }else {
                return response()->json(['error' => 'invalid_credentials_level'], 400);
            }
        }
        catch(\Illuminate\Database\QueryException $e){
            $error = $e->errorInfo;
            return compact('error');
        }
    }
