### ISSUE TITLE
Inconsistent statement

### ISSUE THREAD

**Issue by drjoju** [lazychaser/laravel-nestedset#39]
Hello,

When I execute in Laravel 5 the artisan command:

php artisan ide-helper:generate

An exception appears.

Exception: Declaration of Kalnoy\Nestedset\Node::newFromBuilder() should be compatible with Illuminate\Database\Eloquent\Model::newFromBuilder($attributes = Array, $connection = NULL)
Skipping \Kalnoy\Nestedset\Node.

I see you make the changes in Laravel 4 of 

public function newFromBuilder($attributes = array(), $connection = null)

, but not in Laravel 5.

Do you plan to add this modification in Laravel 5?

Thanks

**Comment by lazychaser** [comment]
See #36 and #38, use v2.3.2

**Comment by drjoju** [comment]
Thanks! You are right. I change

"kalnoy/nestedset": "~2.0@beta",

by

"kalnoy/nestedset": "~2.3.2",

And all works fine.

Thanks and best regards
