### ISSUE TITLE
Create Table with custom columns

### ISSUE THREAD

**Issue by brunsforge** [lazychaser/laravel-nestedset#396]
I am struggeling to modify the column names.

I added "NodeTrait" to the model and have overwritten the get-methods.

```
        use NodeTrait;
	public function getLftName()
	{
	    return 'lft';
	}

	public function getRgtName()
	{
	    return 'rgt';
	}

	public function getParentIdName()
	{
	    return 'parentid';
	}
	public function setParentAttribute($value)
	{
	    $this->setParentIdAttribute($value);
	}
	protected function getScopeAttributes()
	{
	    return [ 'tree_id' ];
	}
```
The migration is still using the default names. When i look into the service provider it uses the "columns"-method of the NestedSet function which simply uses the defined Constants. At this point (line 39 in NestedSet.php) it should use the output of getRgtName(), or not?

What am i doing wrong or is these plugin simply not able to do that?

The nestedSet-Method on the model is simply not using the redefined column names. I am working around that like this atm.

![Image 3](https://user-images.githubusercontent.com/5312061/63517428-45df4a00-c4ef-11e9-9a79-4681e4e4a27d.png)

**Comment by lazychaser** [comment]
> it should use the output of getRgtName(), or not?

it shouldn't

**Comment by brunsforge** [comment]
> > it should use the output of getRgtName(), or not?
> 
> it shouldn't

So there is simply no way to use a different column config with this plugin?
