### ISSUE TITLE
Node deletion

### ISSUE THREAD

**Issue by hobenkr88** [lazychaser/laravel-nestedset#40]
First of all, thanks for all the great work you've done and shared with this project. If I could make one suggestion though, maybe you could include a simple on liner example for deleting a node in the documentation. I know it sounds silly, but long story short, other noobs like me could probably benefit from that. When I initially downloaded your library, I modified deleteNode() to be public because it seemed like that's what I was meant to use. After tracing through your code I found my mistake. but a sentence in the docs of what method to use might help someone else. ...even though this was a slap in the face fix for me :)

Thanks again!

**Comment by lazychaser** [comment]
Hi!

This package is intended to be as much transparent as possible, so nodes deleted as usual models by calling `delete`.

But I still shoul add this to the docs, thanks.
