### ISSUE TITLE
v5 not on Packagist

### ISSUE THREAD

**Issue by stayallive** [lazychaser/laravel-nestedset#401]
Hey @lazychaser thank you for tagging & merging the Laravel 6 support.

Could you take a look why the release is not showing up on Packagist? Usually shouldn't take more than a few minutes unless something is wrong.

> https://packagist.org/packages/kalnoy/nestedset

**Comment by lazychaser** [comment]
Check now

**Comment by stayallive** [comment]
Yeah! Thanks <3
