### ISSUE TITLE
using sortBy() on children

### ISSUE THREAD

**Issue by sinnbeck** [lazychaser/laravel-nestedset#408]
Hi

I am using nested set to load out a questionnaire, but have run into some issues. The order of the children in a block and be different for each user and I was expecting that I could simple reorder them using sortBy(). Now as I've learned, it seems that the original order is kept.
Is there a way to sort them without having to update the database (multiple users can be looking at the same questionnaire at the same time, so reordering them in there would be a mess :)

This is the code I use for sorting. If I inspect $questions in phpstorm using xdebug, I can see that the children are sorted correctly.. But when I run to array they get reverted to their old position.

```
       $traverse = function ($categories) use (&$traverse) {
            $categories->transform(function($category) use ($traverse) {
                $traverse($category->children);
                $category->children = $category->children->sortBy('question_id');
                return $category;
            });
        };

        $traverse($questions);

        return $questions;

**Comment by sajjadgol** [comment]
if position and order of showing category important
please check below  code :  (sorry english !!!! )

`Category::orderBy('_lft','asc')->get()->toTree()`

instead of 

`Category::get()->toTree()`

**Comment by sinnbeck** [comment]
No worries :)
Sadly the issue is with sorting after the data is pulled out. If I want to say shuffle the children, then that would not work.

**Comment by sinnbeck** [comment]
Figured it out. Silly me. Nestedset uses relations for the children :)

```
       $traverse = function ($categories) use (&$traverse) {
            $categories->transform(function($category) use ($traverse) {
                $traverse($category->children);
                $category->setRelation('children', $category->children->shuffle()->values());
                return $category;
            });
        };

        $traverse($questions);

        return $questions;
