### ISSUE TITLE
Extend custom class instead of Eloquent

### ISSUE THREAD

**Issue by cjayx** [lazychaser/laravel-nestedset#41]
Hi!

I am using custom BaseModel (which extends Eloquent) across my whole project. I want \Kalnoy\Nestedset\Node class to extend my BaseModel. Currently I have custom Node class which is identical copy of \Kalnoy\Nestedset\Node. I know this is dirty hack but is there a cleaner and easier way to achieve this?

Thank you in advance!

**Comment by lazychaser** [comment]
Hi, sorry, but there isn't. You could convert your BaseModel to a trait maybe.

**Comment by cjayx** [comment]
I see. Thank you anyway for fast response!
