### ISSUE TITLE
Update performance issue with large data

### ISSUE THREAD

**Issue by leondeng** [lazychaser/laravel-nestedset#420]
Hi @lazychaser , thanks for such an amazing package.

We put it into our product for more than 2 years.
And now one table applied it has about 150k rows, in about 72k trees.

We experience a performance issue when user update their own tree, since the _lft and _rgt are updated the whole table scope.

Is it possible each tree in the table has its own _lft and _rgt values, so any update on the tree will only affects to a much smaller amount of rows?

**Comment by leondeng** [comment]
Just found that I should use scoping, it should be able to solve the performance issue.
Will post result here.

Thanks!

**Comment by nicopenaredondo** [comment]
Hi @leondeng  can you post your solution on this ?
