### ISSUE TITLE
SoftDeletes not working.

### ISSUE THREAD

**Issue by asokol1981** [lazychaser/laravel-nestedset#43]
First of all, спасибо! :)
I add these lines to my Category model and after that SoftDeletes start working as expected. May be I misunderstood something and my code have logical mistakes, check please:

```
protected static function signOnEvents() {
    static::saving(function (Node $model) {
        return $model->callPendingAction();
    });

    static::deleting(function (Node $model) {
        if ($model->hardDeleting()) $model->refreshNode();
    });

    static::deleted(function (Node $model) {
        $model->deleteNode();
    });

    static::restoring(function (Node $model) {
        $model->restoreNode();
    });
}

public function newServiceQuery() {
    return $this->newQuery();
}

protected function restoreNode() {
    if ($last = $this->siblings()->reversed()->first()) {
        $lft = $last->getRgt() + 1;
    } elseif ($this->getParentId()) {
        $parent = $this->parent()->first();
        $lft = $parent->getLft() + 1;
    } else {
        $lft = 1;
    }
    $this->setAttribute(static::LFT, $lft);
    $this->setAttribute(static::RGT, $lft + 1);

    $this->makeGap($lft, 2);
    return true;
}

protected function hardDeleting() {
    return !$this->softDeleting();
}

protected function softDeleting() {
    return static::$_softDelete && !$this->forceDeleting;
}
```
Checks in `QueryBuilder::countErrors()` must exclude rows which are soft deleted.

**Comment by lazychaser** [comment]
What is working unexpected wihtout these modifications?

When I was writing this post, I realized how I can soft delete descendants, more precisely how to restore them if parent is restored.

**Comment by lazychaser** [comment]
Please, update to 2.4.1, remove your modifications and test

**Comment by asokol1981** [comment]
I update and test.
The problem is that the values of `_lft` and `_rgt` are not updated after `restore`. They contain values before `delete`.
Table has 2 categories with _lft and _rgt values: 1-2, 3-4. First node is soft deleted. After that table will contain: 1-2, 1-2. And after restore it must be: 1-2, 3-4 (order doesn't matter), but has: 1-2, 1-2.

**Comment by lazychaser** [comment]
Lft and rgt shouldnt be changed when soft deleted at all
29 íÁÒ 2015 Ç. 20:27 ÐÏÌØÚÏ×ÁÔÅÌØ "asokol1981" <notifications@github.com>
ÎÁÐÉÓÁÌ:

**Comment by asokol1981** [comment]
Ok.

**Comment by lazychaser** [comment]
Ok what? Is this what happens or not?
29 íÁÒ 2015 Ç. 20:47 ÐÏÌØÚÏ×ÁÔÅÌØ "asokol1981" <notifications@github.com>
ÎÁÐÉÓÁÌ:

**Comment by asokol1981** [comment]
SoftDeletes now should work. But I think not to change _lft and _rgt is not right. It will brake result of `Node::getDescendantCount` and may be will brake another expectations. :)

**Comment by lazychaser** [comment]
Well, yeah, but you shouldnt strongly rely on this values. Anyways, i would
wipe soft deleted models from db from time to time.
29 íÁÒ 2015 Ç. 21:05 ÐÏÌØÚÏ×ÁÔÅÌØ "asokol1981" <notifications@github.com>
ÎÁÐÉÓÁÌ:
