### ISSUE TITLE
Maximum function nesting level of '512' reached, aborting!

### ISSUE THREAD

**Issue by jjjrmy** [lazychaser/laravel-nestedset#452]
Hello, I am getting a nesting level error when I am using toTree();
I am using [Laravel Livewire](https://github.com/livewire/livewire) and inside of the component it is giving me the following error.
`ErrorException Maximum function nesting level of '512' reached, aborting!`

It seems to work fine when I do it in a regular controller.
This is the code I am using that is giving me the error.
```
public function mount() {
    $this->quiz = QuizSet::descendantsAndSelf(2)->toTree();
    var_dump($this->quiz);
}
```

**Comment by jjjrmy** [comment]
I think this is an issue with Livewire and not NestedSet

**Comment by arnarstef** [comment]
This is indeed some sort of issue with Livewire.

If someone else stumbles upon this what I did to fix this issue was either set the variable to private for the component class, eager load the 'child' and 'parent' relation like so:

`$this->quiz = Quiz:with(['children', 'parent'])->all()->toTree();`

or convert the results to an array:

`$this->quiz = Quiz:all()->toTree()->toArray();`

**Comment by arnarstef** [comment]
Actually scratch that, I'm still getting some weird behaviour from nestedsets using livewire no matter what I try

**Comment by that0n3guy** [comment]
@arnarstef Did you ever get this to work?

**Comment by sawirricardo** [comment]
> This is indeed some sort of issue with Livewire.
> 
> If someone else stumbles upon this what I did to fix this issue was either set the variable to private for the component class, eager load the 'child' and 'parent' relation like so:
> 
> `$this->quiz = Quiz:with(['children', 'parent'])->all()->toTree();`
> 
> or convert the results to an array:
> 
> `$this->quiz = Quiz:all()->toTree()->toArray();`

I can confirm that switching to private works. But, didn't try to experiment with other solutions though, so probably I assume a temporary fix for now.
