### ISSUE TITLE
fixTree() seems to turn entire table into one tree

### ISSUE THREAD

**Issue by judgej** [lazychaser/laravel-nestedset#454]
I have existing data with many root nodes (no parent) and only a few of those root nodes have descendents, with children pointing to those roots as parents.

When rebuilding the tree, after adding the `_lft` and `_rgt` columns, I expected multiple trees to be created. Those root nodes with no descendents should become trees of one - left and right should be 1 and 2 for each, and parent_id should remain `null`.

Instead, root 1 gets a left and right of 1 and 2, as expected. But then root 2 gets 3 and 4. The next root gets 5 and 6 etc.

The implication of this is that the trees are not independent. If I add a child to one of those root nodes, does it rebuild the entire table again, giving unique numbers to every single left and right? That doesn't seem right. It's slow (this is a big table) and involves locking the entire table instead of just the few nodes that may be involved in inserting a child.

Is this correct? Every tree should be independently numbered, so updating a tree affects only that tree. It does not seem like this is the way it works.

**Comment by judgej** [comment]
Hmm, I think I'm wrong here. The left and right values must be unique across the whole table to keep the nodes in each tree separate. The only way to avoid that would be to hold the root node of each tree in each node of that tree (i.e. a label to identify which tree any node is in, so a query can operate on a single tree without jumping off to another tree sharing the same left or right values). This package clearly does not do that, so this is the way it is designed to work.

**Comment by tarikhagustia** [comment]
Hi @judgej i have same problem too (many root tree in one table). btw do you have any solution with this package?
