### ISSUE TITLE
toTree() How to remove an empty child array from parent node

### ISSUE THREAD

**Issue by hungnm1518** [lazychaser/laravel-nestedset#456]
Hello. Thanks for your package.
I'm using toTree() function to build a tree array. But in a parent node, there is always a child array that appears even though it is empty. How to remove it? Thanks!!!
![image](https://user-images.githubusercontent.com/43890051/80303150-945c8b00-87d8-11ea-82cc-01e3c5ddc087.png)

**Comment by vorsprungRene** [comment]
This worked for me:

        $org_tree = $org_tree->toTree();

        $remove_empty_children = function ($elemente) use (&$remove_empty_children) {
            foreach ($elemente as $element) {
                if($element->children->isNotEmpty()) {
                    $remove_empty_children($element->children);
                } else {
                    $element->unsetRelation('children');
                }
            }
        };

        $remove_empty_children($org_tree);

**Comment by hungnm1518** [comment]
thanks for your reply. 
I've a simple solution.
edit at line 36 in src/Collection.php
Change
```
$node->setRelation('children', BaseCollection::make($children));
```
to
```
if(!empty($children)) {
    $node->setRelation('children', BaseCollection::make($children));
}
```
