### ISSUE TITLE
dropNestedSet is not working with laravel 7

### ISSUE THREAD

**Issue by efmanu** [lazychaser/laravel-nestedset#459]
Hi,
  I have created a table named `items`. The `down `function in migration file is written as below:
```
public function down()
    {
        Schema::table('items', function (Blueprint $table) {
            $table->dropNestedSet();
        });
    } 
```

But, when I try to do `php artisan migrate:rollback` it is not removing the table from database. But it is deleting migration file name from migrations table. 

How can I solve this issue?
Manu

**Comment by bendo01** [comment]
`public function down()
    {
        Schema::connection('connectionName')->dropIfExists('tableName');
    }`

**Comment by GusevDV** [comment]
@efmanu any luck?
I have same issue.

**Comment by serkansahinn** [comment]
Hi @efmanu,
I am not sure why you can't use `$table->dropNestedSet();` probably you have a different problem because i am using laravel 7 too and i don't have any problem with it. I think you should re-install the package or update it. Or you can try this one:

```
use Kalnoy\Nestedset\NestedSet;

...

public function down()
    {
        Schema::table('items', function (Blueprint $table) {
            NestedSet::dropColumns($table);
        });
    }
```

Maybe this is the solution for you.

**Comment by ArtNous** [comment]
is this issue resolved?

**Comment by efmanu** [comment]
> @efmanu any luck?
> I have same issue.

Today I reinstalled the package. Now it is working

**Comment by nivv** [comment]
@efmanu close the issue then

**Comment by efmanu** [comment]
.
