### ISSUE TITLE
Rebuild tree of childrens

### ISSUE THREAD

**Issue by NeekoGta** [lazychaser/laravel-nestedset#476]
I have trouble to rebuild tree of childrens.

I have structure (to test) like this : 

```
$data = [
    [ 
    	'id' => 1, 
    	'name' => 'Item 1', 
    	'children' => [
	    	[
	    		'id' => 3,
	    		'name' => 'Children Item 1'
	    	],
	    	[
	    		'id' => 4,
	    		'name' => 'Children Item 2'
	    	]
    	] 
    ],
    [ 
    	'id' => 2,
    	'name' => 'Item 2' 
    ],
];
```

If I move `Item 2` before `Item 1`, it's ok and saved in database.
But If I move `Children Item 2` before `Children Item 1`, isn't working.

Any idea?
I'm using `rebuildTree`, do I need to use `rebuildSubtree` too?

Thanks!

**Comment by emielmolenaar** [comment]
@NeekoGta Sorry to ping you about an old issue, but how did you fix this?
