### ISSUE TITLE
How to Move a child node to another root?

### ISSUE THREAD

**Issue by mecjos** [lazychaser/laravel-nestedset#480]
How can I move an existing node from one parent to another node's children?

**Comment by ovidiudinu** [comment]
@mecjos did you found a solution? or why did you closed the issue?

**Comment by mecjos** [comment]
> @mecjos did you found a solution? or why did you closed the issue?

There is already a solution in documentation . I missed it out.

**Comment by spacemudd** [comment]
For other people who come here without an answer, in the docs, this section illustrates it:

https://github.com/lazychaser/laravel-nestedset#making-a-root-from-existing-node

```
// #1 Implicit save
$node->saveAsRoot();

// #2 Explicit save
$node->makeRoot()->save();
```
