### ISSUE TITLE
$node->delete() not works after update

### ISSUE THREAD

**Issue by bahaedini** [lazychaser/laravel-nestedset#485]
My first project was on laravel 5.7

I updated it many times, in the last update(laravel 8.18.0 and nestedset 5.0.3)

I have some problems with only a few nodes. I can not delete them. (but other nodes have not any problem!)

`$category->delete();`
(note: all other functions works!)
I get this error

`SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jordan_tir98`.`articles`, CONSTRAINT `articles_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`)) (SQL: delete from `categories` where `id` = 8284)`

I try to fix the table with this command before deleting

`Category::fixTree();`

but it not fix the problem.

Any other advice?

**Comment by ildyria** [comment]
Same issue here.

**Comment by stylder** [comment]
Same issue
