### ISSUE TITLE
Repair tree

### ISSUE THREAD

**Issue by Febalist** [lazychaser/laravel-nestedset#49]
Is there a way to repair broken tree? For example, if `parent_id` of some nodes have been changed manually by SQL and now `Category::countErrors()` return `wrong_parent = 3`.

**Comment by lazychaser** [comment]
This script should return rows with new parent_id for each row that has invalid value:

```sql
SELECT id, parent_id, (select p.id from categories p where c.id <> p.id and c._lft between p._lft and p._rgt order by p._lft desc limit 1) new_parent_id
FROM categories c
HAVING parent_id <> new_parent_id;
```

You can then update the rows in a separte query.

**Comment by Febalist** [comment]
Okay, and what about oddness and duplicates?

**Comment by lazychaser** [comment]
You index nodes by parent and repair _lft, _rgt values. More complex code required, you can basically just rebuild the tree.

**Comment by Febalist** [comment]
Ok, thanks.
