### ISSUE TITLE
Critical: Incompatibe with Laravel ^8.43.0

### ISSUE THREAD

**Issue by lucianholt97** [lazychaser/laravel-nestedset#515]
As of version 8.43.0, Laravel implemented their own `getRelationQuery` method on the `Relation` class which is extended by the `BaseRelation`. The methods don't mean to be compatible, so their signature is completely different.

The error is:
```
Declaration of Kalnoy\Nestedset\BaseRelation::getRelationQuery(Illuminate\Database\Eloquent\Builder $query,  
Illuminate\Database\Eloquent\Builder $parent, $columns = [...]) must be compatible with  
Illuminate\Database\Eloquent\Relations\Relation::getRelationQuery()
```

As a result, the method `getRelationQuery` of `BaseRelation` should be refactored (e.g. with a prefix).

**Comment by squatto** [comment]
For those that land here and don't look at the other issues, this is a dupe of #509 - the fix is to upgrade to version 6
