### ISSUE TITLE
Get nodes of specified level of node

### ISSUE THREAD

**Issue by minhchu** [lazychaser/laravel-nestedset#524]
Hi, thanks for making great package. 

I have a question. How can I get nodes of specified level of a node ?

For example:
```php
$result = Category::withDepth()->find($nodeId)->descendants->having('depth', '=', 1)->get();
```

**Comment by EgorGruzdev** [comment]
```
$result = Category::query()->where('depth', 1)->get();
```

**Comment by minhchu** [comment]
Hi @EgorGruzdev 
It does not work because `depth` is not a **real** column in the database. 

Just found the solution:
```php
Category::first()->descendants()->withDepth()->having('depth', 1)->get()
```

**Comment by EgorGruzdev** [comment]
I'm sorry, but indeed there is no depth column in this package (confused with https://github.com/etrepat/baum).

**Comment by minhchu** [comment]
@EgorGruzdev yep, you can see it in the docs: https://github.com/lazychaser/laravel-nestedset#including-node-depth

Btw, I've just updated my previous comment. Thanks
