### ISSUE TITLE
How to toTree() relation on same model

### ISSUE THREAD

**Issue by rickyanwar** [lazychaser/laravel-nestedset#526]
![image](https://user-images.githubusercontent.com/36995966/126363548-d10b8cc9-6652-4069-aee4-e493e4245200.png)

i have a user model with attributes like this, relation on the same model (user)

![image](https://user-images.githubusercontent.com/36995966/126363677-7a54e492-f8cb-4713-aa76-ab8dd208254b.png)
but when i get data

```
        $children = User::with('children')->get()->toTree();
        return $children;
```
i got nothing nested data, and just 1 of my data is showing 

![image](https://user-images.githubusercontent.com/36995966/126363839-9e5eb834-364d-4d51-92b7-2f45c8af75e8.png)

**Comment by EgorGruzdev** [comment]
Why wake up a relationship if it already exists in the trait Kalnoy\Nestedset\NodeTrait
look \Kalnoy\Nestedset\NodeTrait::children()

and will work 
```
User::query()->get()->toTree();
```

**Comment by rickyanwar** [comment]
![image](https://user-images.githubusercontent.com/36995966/126642156-11623de4-5701-4120-99a0-b04c00f30338.png)
i got nothing, relation to it self, table user 
```
   $children = User::query()->get()->toTree();
   return $children;
```

**Comment by EgorGruzdev** [comment]
Remove relation children() in User::class

**Comment by rickyanwar** [comment]
Thanks it Fix, i was add on migration    NestedSet::columns($table);
