### ISSUE TITLE
Error on update to laravel 5.1.9

### ISSUE THREAD

**Issue by sambadi** [lazychaser/laravel-nestedset#53]
```
 - Removing laravel/framework (v5.1.8)
  - Installing laravel/framework (v5.1.9)
    Downloading: 100%

 [ErrorException]
  Declaration of Kalnoy\Nestedset\Node::append() should be compatible with Illuminate\Database\Eloquent\Model::append($attributes)
```

Into the new version of framework to the "Model" class was added new feature, that have same name as the "Node" class function - append, but have different signature.
https://github.com/laravel/framework/commit/2f96281b79d0c2fe2c705b1b4cd1122e7dbd003e

I apologise for my bad english.

**Comment by lazychaser** [comment]
nice

**Comment by merlinus1** [comment]
I think Kalnoy\Nestedset\Node::append() and Kalnoy\Nestedset\Node::prepend() should be renamed to appendNode() and prependNode() to avoid conflict with Illuminate\Database\Eloquent\Model methods.

That will be breaking change, but I see no other solution

**Comment by lazychaser** [comment]
@merlinus1, yeah, that's what I'm going to do

**Comment by lazychaser** [comment]
v 3.0 fixes this issue
