### ISSUE TITLE
Problems with delete funtion

### ISSUE THREAD

**Issue by stylder** [lazychaser/laravel-nestedset#544]
I have the following code and it throws me the error:
Laravel:
- "laravel/framework": "^8.65",
- "kalnoy/nestedset": "^6.0",

```
 public function destroy($id)
    {
        $node = Node::find($id);
        $node.delete();
        return response()->json($node, 200);
    }
```

`
Error: Call to undefined function App\Http\Controllers\api\v0\delete() in file 
`

**Comment by sinnbeck** [comment]
Php does not use dots but ->
```
$node->delete();

**Comment by stylder** [comment]
> Php does not use dots but ->
> 
> ```
> $node->delete();
> ```
In the documentation it tells me that it is eliminated the way I do it, where did I go wrong?
[Docs](https://github.com/lazychaser/laravel-nestedset#deleting-nodes)
