### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by entexa** [lazychaser/laravel-nestedset#548]
kalnoy/nestedset[v6.0.0, ..., v6.x-dev] require illuminate/support ^7.0|^8.0 -> satisfiable by illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].

  Problem 1
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.

- Only one of these can be installed: illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. 
**laravel/framework replaces illuminate/support and thus cannot coexist with it.**

- Conclusion: don't install laravel/framework v9.0.0 (conflict analysis result)

**Comment by pauldwight** [comment]
There is open PR for adding Laravel 9 Support ( #546 ), hopefully that will get reviewed shortly.
