### ISSUE TITLE
Change the node position

### ISSUE THREAD

**Issue by windhunter89** [lazychaser/laravel-nestedset#55]
Hi, just curious how to change the node position? Which code should I used?
Scenario 1 :
========
Drag Product 2 from Product 1 to Product 3
Before : 
Product 1
-Product 2
Product 3

After :
Product 1
Product 3
-Product 2

Scenario 2:
========
Drag Product 2 to Product 1
Before : 
Product 1
Product 2
Product 3

After :
Product 1
-Product 2
Product 3

Scenario 3:
========
Drag Product 2 from Product 1 to root
Before : 
Product 1
-Product 2
Product 3

After :
Product 1
Product 2
Product 3

**Comment by lazychaser** [comment]
Use `insertBefore`/`insertAfter`

**Comment by windhunter89** [comment]
Hi, insertBefore/insertAfter is only when the neighbor exist right? For example scenario 1 which neighbor should I refer to?

**Comment by lazychaser** [comment]
Then you use `appendNode`:

```php
$product3->appendNode($product2);
```

**Comment by windhunter89** [comment]
Ok it worked. =) Thx
