### ISSUE TITLE
Checking if a node is root 

### ISSUE THREAD

**Issue by ComputerMaverick69** [lazychaser/laravel-nestedset#558]
I just want to know if there's a way to check if a particular node is a root node or a leaf node or even a non-leaf node.
As per the documentation, we can only apply constraints to the query builder.

Can we do something like this? `$node->isRoot();` or `$node->isLeaf();`

We already have 
```
  Constraints

  Various constraints that can be applied to the query builder:

    whereIsRoot() to get only root nodes;
    hasParent() to get non-root nodes;
    whereIsLeaf() to get only leaves;
    hasChildren() to get non-leave nodes;
    whereIsAfter($id) to get every node (not just siblings) that are after a node with specified id;
    whereIsBefore($id) to get every node that is before a node with specified id.
```

**Comment by ao-jhelmich** [comment]
Hey, 

this already can be done

see: https://github.com/lazychaser/laravel-nestedset/blob/3fe245b00f2cdb8ef238f49630ff5979c7369a1c/README.markdown?plain=1#L524

**Comment by ComputerMaverick69** [comment]
Thanks for pointing that out. Not sure that I saw that in the documentation before.
