### ISSUE TITLE
Declaration of Kalnoy\Nestedset\Node::append() should be compatible with Illuminate\Database\Eloquent\Model::append($attributes)

### ISSUE THREAD

**Issue by Spoowy** [lazychaser/laravel-nestedset#57]
This error breaks my stuff since latest update.

ErrorException in Node.php line 1195:
Declaration of Kalnoy\Nestedset\Node::append() should be compatible with Illuminate\Database\Eloquent\Model::append($attributes)

**Comment by lazychaser** [comment]
See #53
