### ISSUE TITLE
My node has no parent, but has ancestors

### ISSUE THREAD

**Issue by robbiemoore** [lazychaser/laravel-nestedset#576]
Hi, I have a mature nestedset with many subtrees. One of my subtrees I think is broken. An example node has no parent, but has ancestors. In order to fix the tree I need to ensure that a node with no parent has no ancestors. 

Here's an example, this is a model from tinker straight after calling `->saveAsRoot()` on the node.
```
App\Models\Department {#6050
    +id: 467283,
    +_lft: 587207,
    +_rgt: 577045,
    +parent_id: null,
    data: "[]",
    +parent: null,
    +ancestors: Kalnoy\Nestedset\Collection {#6068
      all: [
        App\Models\Department {#6067
          +id: 422306,
          +created_at: "2022-12-01 16:55:12",
          +updated_at: "2022-12-01 16:55:12",
          +_lft: 577045,
          +_rgt: 577046,
          ...
 ```
As you can see the node still has ancestors. I have tried the out of the box fix tree functionality, and it doesn't solve the problem. Please could I have suggestions on how to fix my tree?

**Comment by lrljoe** [comment]
Run fixTree() would be my first step!

**Comment by robbiemoore** [comment]
Solved: Our tree was too big for fixTree(). We were able to implement [scoping](https://github.com/lazychaser/laravel-nestedset#scoping), and run fixTree() on each scope. Thanks!

**Comment by Machecek** [comment]
@robbiemoore can you provide example?
