### ISSUE TITLE
Populate from existing data set

### ISSUE THREAD

**Issue by lriggle-strib** [lazychaser/laravel-nestedset#62]
I have a large table of geography data that I'm interested in testing nested sets out with, what is the bets way to generate a node from an already-existing record without having to delete and re-create it?

**Comment by lazychaser** [comment]
Hi. The only way is to write some code that will assign numeric values for _lft and _rgt fields. If this data set is linear, this is rather easy: you just assign `_lft = i * 2;` and `_rgt = i * 2 + 1` where `i` is the index of the geo item. In other case more complex code is required.

**Comment by lazychaser** [comment]
In a `dev-master` version I added `fixTree` method:

```php
Category::fixTree();
```

This should help you.

**Comment by julisana** [comment]
Thanks, I'll give it a look!

**Comment by lriggle-strib** [comment]
Thanks, I'll give it a look!
