### ISSUE TITLE
Transactions on Save

### ISSUE THREAD

**Issue by fntneves** [lazychaser/laravel-nestedset#63]
Hello,

I appreciate your package, it's really useful and easy to use.

One point that I realized is the use of transactions on save() method call. 
They are necessary to mantain consistency, but wasn't better to leave this responsability to developer ?

In case of saving data on controllers under other transactions, it results on nested transactions which is not safe and can decrease performance in certain situations.

Thanks in advance.

**Comment by lazychaser** [comment]
Hi, i investigated this problem before implementing, laravel solves this
issue under the hood without performance penalty. Also, databases cant do
nested transactions anyways ))
06 Сен 2015 г. 15:23 пользователь "Francisco Neves" <
notifications@github.com> написал:

**Comment by fntneves** [comment]
In fact, after digging Laravel code, it maintains only one active transaction after all.
It is clear to me, now.

Thanks !
