### ISSUE TITLE
getAncestors Failing using SQL Server

### ISSUE THREAD

**Issue by uxweb** [lazychaser/laravel-nestedset#64]
Hi!

I really appreciate the work you did with this package, it is awesome!!.

I was using it very well with MySQL for testing, now i started to play with SQL Server and the only issue till now is that when i call the getAncestors() method on a node, it throws an error because of this raw query:

```
select * from [Equipamiento].[area_tipos] where (select _.[lft] from [Equipamiento].[area_tipos] _ where _.[id] = 1 limit 1) between [lft] and [rgt] and [id] <> 1 order by [lft] asc
```

The error says:

```
Msg 102, Level 15, State 1, Line: 1.
Incorrect syntax near 'limit'. (Line 8)
```

This is related to limit 1 that is not supported in SQL Server. If the query is changed to this using "top 1" instead of "limit 1" it will work for any database:

```
select * from [Equipamiento].[area_tipos] where (select top 1 _.[lft] from [Equipamiento].[area_tipos] _ where _.[id] = 1) between [lft] and [rgt] and [id] <> 1 order by [lft] asc
```

The top keyword is widely supported on almost all relational database vendors.

I am stucked for this, i would like to know what do you think!

Thanks!

**Comment by lazychaser** [comment]
`dev-master` should now solve this

**Comment by uxweb** [comment]
Thank you!

**Comment by lazychaser** [comment]
So, is it working? I just don't have SQL Server to test on it. If it works, please close the issue.

**Comment by uxweb** [comment]
Yes!, tried it and it works pretty good!
