### ISSUE TITLE
sorting with JQuery

### ISSUE THREAD

**Issue by xenDE** [lazychaser/laravel-nestedset#66]
Hi,

i want to use the nestedset for managing pages with menu structure.

Now i didn't fully understand the _lft & _rgt columns.
Most JS sort-helpers need an position column for sorting.
i want to use this JS helper for sorting: http://johnny.github.io/jquery-sortable/#

i need to use the _lft column for sorting, right?

what if i change the values of this column?

*auto generated _lft & _rgt with autovalues:*
```
id   _lft     _rgt     _parent     title            slug
1    1        2        NULL        "welcome"        "home"
2    3        8        NULL        "contact"        "contact"
3    4        5        2           "developer"      "contact.dev"
4    6        7        2           "admin"          "contact.admin"
```
*_lft after sorting:*
```
id   _lft     _rgt     _parent     title            slug
1    1        2        NULL        "welcome"        "home"
2    2        8        NULL        "contact"        "contact"
3    1        5        2           "developer"      "contact.dev"
4    2        7        2           "admin"          "contact.admin"
```

do i destroy the tree with this renumbering of _lft?
can if make a `Node::fixTree();` after renumbering and all is back fine?

best regards,
Daniel.

**Comment by lazychaser** [comment]
If you need to drag`n`drop menu items, please refer #50.
If you need simply to order your items within some parent node, you can use another column in db for that

**Comment by xenDE** [comment]
Thanks! Thats working!
