### ISSUE TITLE
Nothing happens..

### ISSUE THREAD

**Issue by AdamGold** [lazychaser/laravel-nestedset#70]
Hi, here's how I am trying to get a category to be a child of another category:
```
$category->appendTo($parentCategory)->save()
```
both $category and $parentCategory are an instance of Node class.
The category saves fine, but with the default values in the _lft, _rgt and parent_id.. same thing that would have happened if I used save() alone without appendTo. What am I missing?

**Comment by lazychaser** [comment]
Are you using some plugins to the eloquent?

**Comment by AdamGold** [comment]
I am not using any plugins.

**Comment by lazychaser** [comment]
Show me your model definition and also complete code where you trying to save the model.

**Comment by AdamGold** [comment]
@lazychaser Thank you for the quick replies.
```
use \Model\Traits\PaginationTrait;
use \Kalnoy\Nestedset\Node;

class Category extends Node
{
    use PaginationTrait;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'categories';

    /**
     * The db connection associated with the model.
     *
     * @var string
     */
    protected $connection = 'site';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'english_name', 'single_name', 'adult', 'icon'];
}
```

The code that saves the model:
```
$category = new Category([
    'title' => $title,
    'description' => $this->params['description'],
    'english_name' => $englishName,
    'single_name' => $this->params['single_name'],
    'adult' => ($this->params['adult'] == 0 || $this->params['adult'] == 1) ? $this->params['adult'] : 0
]);

// handle parent
$parentId = $this->params['parent'];
if ($parentId != 0) {
    $parentCategory = Category::find((int)$parentId);
    if (empty($parentCategory))
        throw new FormException(_('Parent category does not exist.'));
    $category->appendTo($parentCategory)->save();
} else {
    $category->saveAsRoot();
}
```

**Comment by lazychaser** [comment]
First of all, check whether parentId is really there.
Second, you can set `parent_id` attr directly and it will do the job for you.

**Comment by AdamGold** [comment]
@lazychaser I checked, it is there. I can set the ```parent_id``` directly but what about the _lft and _rgt attributes?

**Comment by lazychaser** [comment]
This package does the same thing behind the scenes as you do.
You'll have to figure it on your own since this basic operation is well tested. And what is pagination trait, exactly?

**Comment by AdamGold** [comment]
@lazychaser Isn't the package supposed to handle all the nested-sets related stuff for me? So I won't need to manually adjust the ```lft```, ```rgt``` and ```parent_id``` attributes?

The pagination trait is a custom scope I made for a couple of my models.

**Comment by lazychaser** [comment]
See the [docs](https://github.com/lazychaser/laravel-nestedset#appending-and-prepending-to-the-specified-parent). You can set `parent_id` and the package will append the node to the specified parent (or save it as root if `parent_id` is null). In your code, just make really sure that `$category->appendTo` line as actually executed and not `saveAsRoot`.

**Comment by AdamGold** [comment]
@lazychaser Okay so I tried to set the parent_id manually without using appendTo:
```
           $category = Category::create([
                'title' => $title,
                'description' => $this->params['description'],
                'english_name' => $englishName,
                'single_name' => $this->params['single_name'],
                'adult' => ($this->params['adult'] == 0 || $this->params['adult'] == 1) ? $this->params['adult'] : 0,
                'parent_id' => $parentId
            ]);
```
I made sure ```$parentId``` is a valid value. Anyway, the record gets inserted to the database with a null ```parent_id``` and 0 in both ```_rgt``` and ```_lft```.

**Comment by lazychaser** [comment]
Ok, you never told that lft and rgt are zero. Seems like some other component interfeers with the default eloquent behavior. Nestedset packages utilizes events to achieve its goal.

**Comment by AdamGold** [comment]
@lazychaser I am quite sure the events don't fire. Maybe it's because I am using native Eloquent ORM and I haven't configured something like I should have. I will look into that, but maybe you have an idea?

**Comment by lazychaser** [comment]
That's 100% an issue root! Check whether events are firing:

```php
Category::saving(function () { dd('saving'); });
```

**Comment by AdamGold** [comment]
@lazychaser You used the function ```dd```, but I am not using Laravel.. Aren't events supposed to fire even without Laravel, just Eloquent ORM?

**Comment by AdamGold** [comment]
@lazychaser I got the events to work and now your plugin works. Thank you very much for all your support!

For anyone who is using native Eloquent and the events don't fire (why would they, I haven't configured them to), add this line of code after the ```bootEloquent``` method:
```
/* the use section you are going to need */
use Illuminate\Events\Dispatcher;
use Illuminate\Database\Eloquent\Model;

/* the code to make the events fire */
Model::setEventDispatcher(new Dispatcher());
```

**Comment by lazychaser** [comment]
Good to hear that you've solved your issue!
