### ISSUE TITLE
Check if node is a leaf node?

### ISSUE THREAD

**Issue by uxweb** [lazychaser/laravel-nestedset#72]
Hi @lazychaser 

I've been using this awesome package you made, i really love it.

I'm facing a requirement where i need to get all the leaf nodes, is there a method to get this?, something like whereIsLeaf()?

That would be great to have!

Thanks!

**Comment by lazychaser** [comment]
Thanks, @uxweb!

You can filter down to leaf nodes using this raw where statement:

```php
$query->whereRaw('_rgt - _lft == 1');
```

**Comment by uxweb** [comment]
@lazychaser 

Thank you!
