### ISSUE TITLE
Move existing node to specific position

### ISSUE THREAD

**Issue by mgsmus** [lazychaser/laravel-nestedset#73]
Let's say there are 6 nodes in a parent. I want to insert/move a node into 4th position directly but I don't have any info about other nodes. Is there a way to do this?

**Comment by lazychaser** [comment]
To get fourth child:

```php
$parent->children()->defaultOrder()->skip(3)->first();
```

Make sure to check whether the result is not null and is not the same node you are trying to move (i.e. already in desired position).

**Comment by mgsmus** [comment]
Thanks! Why didn't I think of that, I was using jstree and even though I had parent_id, I was focused on the node all the time.
