### ISSUE TITLE
Node as a Trait?

### ISSUE THREAD

**Issue by ddimaria** [lazychaser/laravel-nestedset#75]
Have you considered refactoring this as a trait so that it isn't required to extend Node?  If not, I can do this in a PR if you think it would be useful as I need that functionality for a project I'm working on.  Let me know.  Thanks! -David

**Comment by lazychaser** [comment]
>  If not, I can do this in a PR if you think it would be useful

What do you mean?

**Comment by ddimaria** [comment]
You currently have to extend Node rather than extend Eloquent for your package to work.  I created a PR converting this to a PHP Trait (http://php.net/manual/en/language.oop5.traits.php), which is more flexible and allows for multiple inheritance of model traits (see https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/SoftDeletes.php as an example).

**Comment by pet1330** [comment]
This is closed by #76. The documentation in [the model](https://github.com/lazychaser/laravel-nestedset#the-model) section of the readme.md file needs updating though :smile:

**Comment by lazychaser** [comment]
Done
