### ISSUE TITLE
how can i change table categories name?

### ISSUE THREAD

**Issue by nhanco** [lazychaser/laravel-nestedset#77]
After do all the package need to make a table name categories . How can i change it to  news_categories ?

**Comment by lazychaser** [comment]
You can give your table any name you want

**Comment by nhanco** [comment]
Can you tell me how to do that ?
thanks so much.

**Comment by lazychaser** [comment]
https://laravel.com/docs/5.2/eloquent#eloquent-model-conventions

**Comment by nhanco** [comment]
Thank so much. And i'm sorry about my bad with laravel and english.

**Comment by lazychaser** [comment]
Good luck!
