### ISSUE TITLE
Model  / Single Table Inheritance - "parent_id" sets/unsets (null) itself.

### ISSUE THREAD

**Issue by gritdigital-mibu** [lazychaser/laravel-nestedset#78]
Hi there,

    laravel/framework v5.1.29
    kalnoy/nestedset v3.1.2

Firstly thank you for sharing such a great plugin and forgive me if this is being caused by something unrelated...   
    
    $post->update(['parent_id' => 2]);
    dd($post);
    
This produces the following output (as I'd expect):
    
        [
        "id" => 8
        "_lft" => 20
        "_rgt" => 21
        "parent_id" => 2
    ]
    
If I update a second time with the same logic I get the following:

    [
        "id" => 8
        "_lft" => 21
        "_rgt" => 22
        "parent_id" => null
    ]
    
It just seems to set and unset itself? I don't understand why it would behave like this as I'm always specifying the parent_id as 2?
    
This behaviour also happens when using fill()->save();

It doesn't happen however if I do:

    $post->parent_id = 2;
    $post->save();
    
This only happens on my "Post" model but works fine on other models in my application.

I am using [https://github.com/Nanigans/single-table-inheritance](https://github.com/Nanigans/single-table-inheritance) so my Post model is using the SingleTableInheritanceTrait.

It uses a global scope which applies a whereIn() to all model queries and and an observer which listens for the ::saving() event.
Even if I comment this out I still get the same behaviour.

    //static::observe(new SingleTableInheritanceObserver());
    

I understand I'm asking you to support a potential conflict with another plugin but even if you could push me in the right direction to debug it I'd be very grateful.

**Comment by gritdigital-mibu** [comment]
$post->update(['parent_id' => 2]);    
    
    $method = 'action'.ucfirst(array_shift($this->pending));
    var_dump($method);
        
First save...

    actionAppendOrPrepend()
    
Then refreshing (exact same behaviour)

    actionRoot()
    
So it thinks it's a root node :(

**Comment by lazychaser** [comment]
After updating the model using `$post->update` what you get in the database? It seems to me that `parent_id` is not saving. Maybe because it's not in `$persisted` attributes?

**Comment by gritdigital-mibu** [comment]
It's updating _lft, _rgt and parent_id in the DB - it's quite bizarre!

**Comment by lazychaser** [comment]
1. You're executing `$node->update([ 'parent_id' => 2 ]);`
2. After the request is finished, database now has correct parent_id, which is 2.
3. In next request, same model has parent_id of null while database has correct value

Right?

**Comment by gritdigital-mibu** [comment]
Apologies for the slow reply.

I am executing `$node->update([ 'parent_id' => 2 ]);` which saves as parent_id 2 in the database. If I execute the exact same thing again `$node->update([ 'parent_id' => 2 ]);` parent_id resets itself to null (when it should be 2!).

Cheers,

**Comment by lazychaser** [comment]
Ah, that's because your plugin overrides `newFromBuilder` which is used to reset current action for existing models. https://github.com/lazychaser/laravel-nestedset/blob/v4/src/Node.php#L742
You just need to override newFromBuilder in your model and call `clearAction` there

**Comment by lazychaser** [comment]
But, actually, I think I can get rid of this dependency entierly.

**Comment by gritdigital-mibu** [comment]
Amazing! If you could that would be excellent - really appreciate your help!

**Comment by lazychaser** [comment]
Don't close the issue yet

**Comment by gritdigital-mibu** [comment]
Thank you so much for your help, everything is now working beautifully!
    
    use SingleTableInheritanceTrait {
        newFromBuilder as stiNewFromBuilder;
    }

    public function newFromBuilder($attributes = array(), $connection = null)
    {
        $instance = $this->stiNewFromBuilder($attributes, $connection);
        $instance->clearAction();

        return $instance;
    }

**Comment by lazychaser** [comment]
This is now has been fixed in `4.1.0@dev`. The release is soon.

**Comment by gritdigital-mibu** [comment]
Excellent, thank you!
