### ISSUE TITLE
Set is broken but fixTree return null

### ISSUE THREAD

**Issue by hiendv** [lazychaser/laravel-nestedset#82]
I have a nested set which contains about 5200 nodes. The `isBroken()` it returns `true` but `fixTree()` always returns `null`. Is there any problem with a large set? 
```
{
    "name": "kalnoy/nestedset",
    "version": "v4.0.1"
}
```

**Comment by lazychaser** [comment]
Please provide an output of `countErrors()` function.

**Comment by hiendv** [comment]
Sorry for the late response. Here's my result from tinker
```php
Psy Shell v0.6.1 (PHP 7.0.1-1+deb.sury.org~trusty+2 — cli) by Justin Hileman
>>> FooBar::isBroken()
=> true
>>> FooBar:: countErrors()
=> [
     "oddness" => 5,
     "duplicates" => 20,
     "wrong_parent" => 0,
   ]
>>> FooBar::fixTree()
=> null
```

**Comment by lazychaser** [comment]
Are you using soft deletes?

**Comment by hiendv** [comment]
No, I'm not. Could you explain `oddness` and `duplicates`?

**Comment by lazychaser** [comment]
`oddness` means there are nodes that have invalid `_lft`/`_rgt` values (lft > rgt or (rgt - lft) is divided by two)
`duplicates` means that some nodes have same `_lft`/`_rgt` values

**Comment by hiendv** [comment]
They share the same `parent_id`, `_lft` and `_rgt` are both `0`

**Comment by lazychaser** [comment]
I guess the only reason of this issue is that those nodes have `parent_id` pointing to a node that doesn't exists. This fixing algorithm is not aware of this case.

**Comment by hiendv** [comment]
Well, they are, indeed. I should have checked the _parent_ sooner, sorry. Thank you so much !

**Comment by lazychaser** [comment]
I think those nodes should be saved as roots when fixing the tree. Also, setting up a foreign key would be nice

**Comment by hiendv** [comment]
@lazychaser In my case, the `parent_id` is optional. At the first place, I thought using `NULL` in foreign keys is a little bit tricky but I was wrong, a parent_id mutator is fine ! Thank you ;)

**Comment by hiendv** [comment]
@lazychaser Sorry, I'm unable to add the foreign key to the current schema of the set. Any advices?
```sql
alter table `foo_bar` add constraint foobar_parent_id_foreign foreign key (`parent_id`) references `foo_bar` (`id`) on delete cascade;
```

**Comment by lazychaser** [comment]
This means that there are still nodes that have invalid parent_id value. This might help:

```sql
select * from foo_bar where parent_id is not null and not exists (select 1 from foo_bar p where p.id = foo_bar.parent_id)
```

This query will display nodes pointing to invalid parents.

**Comment by hiendv** [comment]
@lazychaser Thank you so much. It's clear now !

**Comment by lazychaser** [comment]
Great, glad to help
