### ISSUE TITLE
Loading specific tree with where clause

### ISSUE THREAD

**Issue by ParadoxNL** [lazychaser/laravel-nestedset#83]
I have a database with over 500 categories, and to load them with the query below gives the perfect result, however it would be awesome if we could apply a where cause, that would reduce the amount of data. 

Now:
```php
Category::defaultOrder()->get()->linkNodes()->toTree()
```

New feature:
```php
Category::defaultOrder()->where('id', '=', '2')->get()->linkNodes()->toTree()
```

To make my point a bit more clear:
![Wikipedia nested model](https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/NestedSetModel.svg/701px-NestedSetModel.svg.png)

It's like saying give me only the men's category, and build the tree down from that point.

**Comment by ParadoxNL** [comment]
This managed to do the trick for me:

```php
Category::defaultOrder()->with('descendants')->where('parent_id', 2)->get()->linkNodes()->toTree()
```

**Comment by lazychaser** [comment]
This will do the trick:

```php
$parent = Category::find(2);
$nodes = $parent->descendants->toTree($parent);
```

Now `$nodes` contains every child of `$parent` with filled `children` relationship.

**Comment by lazychaser** [comment]
This is equivalent:

```php
$parentId = 2;
$nodes = Category::descendantsOf($parentId)->toTree($parentId);
```

**Comment by ParadoxNL** [comment]
Awesome, thanks for the answer. Might be a good idea to add this to the documentation?

**Comment by lazychaser** [comment]
Yeap, doing it right now
