### ISSUE TITLE
Custom  column names

### ISSUE THREAD

**Issue by naneri** [lazychaser/laravel-nestedset#87]
Would that be a good idea to add a custom column names? For example if somebody migrates the project from another framework and already has left,right and parent_id columns in mysql but their names are different. 

I think possibility of renaming the columns in config would be good.

**Comment by lazychaser** [comment]
Simply override getlftname, getrgtname, getparentidname methods. Also, add
parent id mutator (if parent id name changed). I can explain better a bit
later
27 Фев 2016 г. 12:13 пользователь "naneri" <notifications@github.com>
написал:

**Comment by lazychaser** [comment]
These methods: https://github.com/lazychaser/laravel-nestedset/blob/master/src/NodeTrait.php#L833

If the name of parent id attribute is changed, you need to define its mutator:

```php
public function setMyCustomParentAttribute($value)
{
    $this->setParentIdAttribute($value);
}
```
