### ISSUE TITLE
Can't implement on Laravel 5.2

### ISSUE THREAD

**Issue by sebastianvirlan** [lazychaser/laravel-nestedset#89]
Hi, I am trying to use nestedset on my website but I did no succeeded to implement it.

So I terminal:

`composer require kalnoy/nestedset
`
then in app.php

`        'NestedSet' => Kalnoy\Nestedset\NestedSet::class,
`

in migration:

`        Schema::create('menu_filters', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->text('filter');
            $table->integer('count');
            NestedSet::columns($table);
        });
`

and created successfully the table but in model I can't add the:

```
use Kalnoy\Nestedset\NodeTrait;
.................................
use NodeTrait;
```

because does not exist.
Also I observed that the files that composer added to the project are older than the one on github here. For example in collection.php I don't have: toFlatTree method.

**Comment by lazychaser** [comment]
These features are only available in unstable version `v4.1.0@dev`. Sorry for this inconvinience. Stable release is upcoming.

**Comment by sebastianvirlan** [comment]
Great. Thank you. Also I managed to integrate your code on my needs.

```
        $nodes           = MenuFilter::get()->toTree();

        $traverse = function ($categories, $prefix = '<li>', $suffix = '</li>', $children = '<li class="sidebar-menu-has-children"></li>') use (&$traverse) {
            foreach ($categories as $category) {
                echo PHP_EOL.$prefix.' '.$category->name.' ('.$category->count.')'.$suffix;
                $traverse($category->children, $children.'<ul>', $suffix.'</ul>');
            }
        };

        echo '<ul class="sidebar-menu">';
        $traverse($nodes);
        echo '</ul>';
        return view('pages.index', ['properties' => $properties, 'property_types' => $property_types, 'nodes' => $nodes]);
```

Works like charm, thank you. But as I am new to laravel can you indicate me how to send this to view and have a slim controller? Using a helper?

http://www.sitepoint.com/laravel-blade-recursive-partials/

I tried to use this but does not satisfy my needs. So how can I send to view best practice?

**Comment by lazychaser** [comment]
@sebastianvirlan what's wrong with the recursive partial?

I personally use [this](https://github.com/lazychaser/illuminate-menu) to render menus. I simply override base class to convert category to menu item:

```php
class CategoriesMenu extends MenuBuilder
{
    /**
     * Normalize an item to be consumable by `item` method.
     *
     * @param mixed $key
     * @param mixed $value
     *
     * @return array|string
     */
    protected function normalizeItem($key, $value)
    {
        if ($value instanceof Category)
        {
            $value = [
                'label' => $value->getMenuTitle(),
                'url' => \UrlTo::category($value),
                'badge' => $value->products_count ?: null,
                'items' => isset($value->children) ? $value->children : null,
                'visible' => $value->is_visible,
            ];
        }

        return parent::normalizeItem($key, $value);
    }

}
```

There are many overridable properties & methods that allow customizing output html.

If you still want to stick to simple function, you can define `$traverse` as a global helper function (but give it a more reasonable name). I'd prefer recursive partials from two.
