### ISSUE TITLE
Creating Node model in observer fails

### ISSUE THREAD

**Issue by Propaganistas** [lazychaser/laravel-nestedset#90]
Hi

Suppose the following setup where a node model is being created as a consequence of the creation of `ModelA`:

```php
class NodeModel extends Model
{
    use NodeTrait;
}

class ModelA extends Model {

    protected static function boot()
    {
        parent::boot();

        static::created(function ($model) {
            NodeModel::create([]);
        });
    }
}
```

Unfortunately this doesn't work. On `dd`'ing the `NodeModel::create` line a model is effectively returned with `$exists` set to true, but it simply isn't persisted to the database.
Upon removing the `NodeTrait` the setup *does* work and the NodeModel can be found in the database as expected.

Can someone replicate this?

**Comment by lazychaser** [comment]
I guess this has something to do with transactions. Ill be unable to investigate this for few days

**Comment by Propaganistas** [comment]
No problem.

There's something odd going on! Take a look at the attached screenshot... Creation of the NodeModel (`MenuItem`) succeeds and it is even returned in the subsequent fetch call, but as soon as the app reboots all is gone...

![screenshot](https://cloud.githubusercontent.com/assets/6680176/13579459/f8b90a02-e49d-11e5-93fe-5621c31ec1e6.png)

**Comment by lazychaser** [comment]
Are you using scoping?

**Comment by lazychaser** [comment]
Seems like transactions do not apply. Try calling DB::commit() before
exiting tinker

**Comment by Propaganistas** [comment]
No.. I haven't overridden `boot()` and as you can see there's no scope over there.
`DB::commit()` before exiting tinker results in a never-ending call... It just keeps calculating...
![commit](https://cloud.githubusercontent.com/assets/6680176/13579759/5e0ce77e-e49f-11e5-9813-3d8c25814a24.png)

**Comment by lazychaser** [comment]
Hmm. What db provider is used in your example?

**Comment by Propaganistas** [comment]
I'm using SQLite for local development...

**Comment by lazychaser** [comment]
Same for unit tests. Any specific settings? Or fresh laravel?

**Comment by lazychaser** [comment]
Try running this:

```php
DB::beginTransaction();
DB::table('menu_items')->insert([ 'menu_id' => 2 ]);
DB::commit();
```

**Comment by Propaganistas** [comment]
Running those (after adding `_lft` and `_rgt` attributes) works flawlessly.

**Comment by lazychaser** [comment]
Then this:

```
DB::beginTransaction();
DB::table('menu_items')->insert([ 'menu_id' => 2 ]);
DB::beginTransaction();
DB::table('menu_items')->insert([ 'menu_id' => 2 ]);
DB::commit();
DB::commit();
```

**Comment by Propaganistas** [comment]
Works as expected, both records are present in the database.

**Comment by lazychaser** [comment]
That's interesting. Now find original `NodeTrait` and in `bootNodeTrait` method comment out everything related to transactions. Then try to create a node.

**Comment by Propaganistas** [comment]
Works as well now! I really don't have a clue what's going on...

**Comment by lazychaser** [comment]
Now replace every `beginTransaction` to `Log::info('beginTransaction')` and `commit` to `Log::info('commit')`. Run your code and check `laravel.log`, what it says?

**Comment by Propaganistas** [comment]
Ah, look at this, it's missing a commit

```
[2016-03-07 20:40:34] local.INFO: beginTransaction  
[2016-03-07 20:40:34] local.INFO: beginTransaction  
[2016-03-07 20:40:34] local.INFO: commit  
```

**Comment by lazychaser** [comment]
Ok, now mark each method with event in where it was called. For `saving` it'll be `Log::info('saving: begin');`, for `saved` `Log::info('saved: commit');` and so on

**Comment by Propaganistas** [comment]
```
[2016-03-07 20:44:02] local.INFO: saving: beginTransaction  
[2016-03-07 20:44:02] local.INFO: saving: beginTransaction  
[2016-03-07 20:44:02] local.INFO: saved: commit  
```

**Comment by lazychaser** [comment]
Hmm, put `Log::info('boot');` at the start of `bootNodeTrait`

**Comment by Propaganistas** [comment]
[2016-03-07 20:47:26] local.INFO: boot  
[2016-03-07 20:47:26] local.INFO: saving: beginTransaction  
[2016-03-07 20:47:26] local.INFO: saving: beginTransaction  
[2016-03-07 20:47:26] local.INFO: saved: commit

**Comment by Propaganistas** [comment]
Sorry, you can ignore the second saving event, it was something from a base model. I've commented that out as well, but the problem still exists.

**Comment by lazychaser** [comment]
Base model?

**Comment by Propaganistas** [comment]
```php
class BaseModel extends Model
{
   public static function boot() {
      parent::boot();

      // static::saving(function(){....});  --> I've commented this out
}

class MenuItem extends BaseModel
{
   use NodeTrait;
}
```

**Comment by lazychaser** [comment]
Now please add some basic model not related to nodes and add saving/saved events and put logging there. Just to make sure that whether this related to nodes or not

**Comment by Propaganistas** [comment]
Well as described in the OP if I remove the `NodeTrait` the `NodeModel` does get created during the `created` event of ModelA. Events are firing as expected, with or without the model being a node...

Another peculiarity I just discovered: if the `created` event of Model A is removed and "moved" to an explicit call in a controller like this:

```php
public function postIndex(Request $request)
{
    $model = ModelA::create(...); // is created succesfully.
    $node = NodeModel::create(...); // dd says created succesfully but NOT found in database.

    return redirect()->back();
}
```
or
```php
public function postIndex(Request $request)
{
    $node = NodeModel::create(...); // dd says created succesfully but NOT found in database.

    return redirect()->back();
}
```

So it seems the model doesn't persist in any case...

**Comment by lazychaser** [comment]
Are you using some other traits, extensions to the framework? What version
of laravel exactly (with minor)?
08 марта 2016 г. 9:29 пользователь "Propaganistas" <notifications@github.com>
написал:

**Comment by Propaganistas** [comment]
Laravel 5.2.22

The base model I spoke about earlier implements dimsav/translatable, laracasts/presenter and watson/validating. I commented out all of these traits and it still doesn't work. As soon as NodeTrait is commented out as well the model does get saved...

**Comment by lazychaser** [comment]
Hi. What version of php are you using?

**Comment by Propaganistas** [comment]
PHP 7.0.2

**Comment by lazychaser** [comment]
Try this on 5.6

2016-03-12 10:11 GMT+03:00 Propaganistas <notifications@github.com>:

> PHP 7.0.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lazychaser/laravel-nestedset/issues/90#issuecomment-195676808>
> .
>



-- 
Best regards, Alexander Kalnoy.

**Comment by Propaganistas** [comment]
Switching to 5.6 was to no avail unfortunately..

**Comment by Propaganistas** [comment]
Hello

I've managed to track down the issue. Some time ago when contributing to another package I tested some code by directly modifying an Illuminate vendor file. Seems that I forgot to remove a line.

Sorry for wasting your time. I feel silly.
