### ISSUE TITLE
New features for v3 for Laravel 5.1 LTS

### ISSUE THREAD

**Issue by marsd** [lazychaser/laravel-nestedset#92]
Hi, 

I am wondering if the new (and future) features implemented for v4 will be implemented in v3 as well? Due to LTS and project requirements, I am unable to upgrade to 5.2. 

Multi-tenancy will be extremely welcome in my current project.

**Comment by lazychaser** [comment]
Sorry, no new features will be implemented in v3. Only bug fixes if any occur.
