### ISSUE TITLE
undefined method toBase()

### ISSUE THREAD

**Issue by goodmove** [lazychaser/laravel-nestedset#95]
Hi, when I try to remove or update category on backend, i get message "Call to undefined method Illuminate\Database\Query\Builder::toBase()". Metod toBase() absent in class QueryBuilder and Builder.  My model Category extends SleepingOwlModel. Can this problem?

**Comment by lazychaser** [comment]
`toBase()` should be in `Illuminate\Database\Eloquent\Builder` class since laravel 5.2

**Comment by goodmove** [comment]
спасибо, заработало
