### ISSUE TITLE
rebuildTree()  preg_replace() error

### ISSUE THREAD

**Issue by mmakhno** [lazychaser/laravel-nestedset#96]
Hi!
Thanks for this package :)

When I'm trying to use rebuildTree() method for my $data array I'm getting error:
> ErrorException in helpers.php line 740: preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

It works Ok when updating simple array like ['id' => '1], but when array looks like [[ 'id' => 1, 'children' => ['id' => 2]], ['id' => 3 ]]  it throws exception.

Maybe somebody can advise me how to solve this problem :)

**Comment by lazychaser** [comment]
Children should be an array of arrays
01 апр. 2016 г. 4:20 пользователь "Mihail" <notifications@github.com>
написал:

**Comment by mmakhno** [comment]
The same problem.

**Comment by mmakhno** [comment]
I think I've found small bug:
**src/QueryBuilder.php**
`line 878: buildRebuildDictionary()`
`line 901: $model->fill($itemData)->save();`
saves all data from $itemData array. But in the case when it has 'childen' array it will throw exception. So the solution it to pass $itemData array withour 'children'.

**Comment by lazychaser** [comment]
`children` should not be on `fillable` array

**Comment by mmakhno** [comment]
Yes! 
There was no $fillable array in the model :)
Thank you!

**Comment by jeromegamez** [comment]
I have the same issue with version 4.1.5 (Laraval 5.2) when I want to seed the table:

```php
// Model
namespace App;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class Genre extends Model
{
    protected $guarded = ['id'];

    protected $fillable = ['name', 'parent_id'];

    public $timestamps = false;

    use NodeTrait;
}
```

```php
// Seeder

use Illuminate\Database\Seeder;
use App\Genre;

class GenreSeeder extends Seeder
{
    private static $genres = [
        'genre_1' => [
            'name' => 'genre_1',
            'children' => [
                ['name' => 'sub_1_1'],
                ['name' => 'sub_1_2'],
                ['name' => 'sub_1_3'],
            ],
        ],
        'genre_2' => [
            'name' => 'genre_2',
            'children' => [
                ['name' => 'sub_2_1'],
                ['name' => 'sub_2_2'],
                ['name' => 'sub_2_3'],
            ],
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Genre::rebuildTree(self::$genres);
    }
}
```

I also tried it with a non-indexed array, as well as without `parent_id` in the fillables, sadly without success...

Do you have a hint what might be the issue?

**Comment by jeromegamez** [comment]
Upon debugging, I'm seeing that Laravel is interpreting `children` as fillable, because the the `$ungarded` attribute in the Model is set to `true`.

**Comment by lazychaser** [comment]
You should either use `guarded` or `fillable` properties, not both. Anyway, I excluded `children` when filling the item.
