### ISSUE TITLE
How to Limit the Children the node can have?

### ISSUE THREAD

**Issue by masterpowers** [lazychaser/laravel-nestedset#98]
I know by default the package allows infinite children... in unlimited depth...
but i wanna make it limit only up to 2 children per node per depth...
How can i Achieve this effect?

**Comment by lazychaser** [comment]
You mean there should be at most 2 generations?

```
Root
- Generation 1
-- Generation 2
--- NOT ALLOWED
```

**Comment by kampit** [comment]
```
$nodes = User::descendantsOf($id)->toTree($id);

A
- B
-- C
---- D skip
- E
-- F 
---- G skip
```

How do I limit the children looks like above?

**Comment by yamamz** [comment]
how to achieve this problem.. I have same problem
