### ISSUE TITLE
up() / down() doesn't work in v3 aswell

### ISSUE THREAD

**Issue by InToSSH** [lazychaser/laravel-nestedset#99]
Hi, I have noticed there is a problem with up() / down() functions, and that it has been fixed in v4 in this issue #81 , however I have a big project based on L5.1 and I am unable to upgrade to L5.2. 
Could you please fix this in v3 branch aswell? My symptoms are exactly the same as in the #81 issue, also using the same package (dimsav/laravel-translatable). 
Thanks

**Comment by lazychaser** [comment]
Should work now

**Comment by InToSSH** [comment]
Thanks a lot @lazychaser , it works now.. Have a cup of coffee on me :)

**Comment by lazychaser** [comment]
Thanks! =)
